Golnoush taran/exchange show owner
CMPUT301F20T24/Unlibrary pull request #108
Opened 2020-11-16 03:44 UTC by ghassanzadeh

# Summary
- This PR is a similar implementation as what @Taranjot-Singh did for getting the list of requesters on library fragment. Here, we only have one owner for each book displayed on exchange detailed bookview.
- The layout for owner is also added onto fragment_unlibrary_book_details.xml

![exchange_book_owner](https://user-images.githubusercontent.com/43598866/99210392-a82b0700-2793-11eb-9e8f-0ef9fab9675e.PNG)

# TODO
- Show the owner on unlibrary detailed bookview
- Remove the profile icon for the owner if not needed (nit)

2020-11-16 16:49 UTC, calebschoepp reviewed
Great work Golnoush. Left a few comments and questions. Didn't comment on any of the changes that Taran made b/c I'm assuming you will rebase on top of his PR.

2020-11-16 16:49 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBookDetailsFragment.java
> +
Nit: extra newline

2020-11-16 16:49 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +import com.example.unlibrary.library.LibraryViewModel;
Why is this being imported if there is no new functionality in this file?

2020-11-16 16:49 UTC, calebschoepp commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:4.0.2'
Any reason in particular for this change?

2020-11-17 03:32 UTC, ghassanzadeh commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:4.0.2'
Ah i updated the gradle on my android studio, and commited all the changes.

2020-11-17 03:52 UTC, calebschoepp requested changes
Looks like your PR will merge before Taran's so I'm putting the comments I had on his PR here to fix them. Other than that I think this is ready to merge once you've addressed the comments.

2020-11-17 03:52 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
>          LibraryViewModel mViewModel = new ViewModelProvider(requireActivity()).get(LibraryViewModel.class);
Make this a member variable so that we don't need to get it twice

2020-11-17 03:52 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +        LibraryViewModel mViewModel = new ViewModelProvider(requireActivity()).get(LibraryViewModel.class);
Make this a member variable so that we don't need to get it twice

2020-11-17 03:52 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/RequestersRecyclerViewAdapter.java
> +package com.example.unlibrary.library;
File header.

2020-11-17 06:53 UTC, calebschoepp approved these changes
LGTM!

2020-11-17 15:42 UTC, merged