Taranjot/library accepting requests
CMPUT301F20T24/Unlibrary pull request #114
Opened 2020-11-19 03:24 UTC by Taranjot-Singh

# Summary
- List of features this PR will add

# Screenshots
- If you're working on UI

# TODO
- List of tasks that is too big for this PR and will be done in future PRs or some known issues to fix
- Don't forget to create new tasks to monitor these

Closes insert-issue-number-here

2020-11-19 17:33 UTC, calebschoepp requested changes
Great work @Taranjot-Singh , lot of good functionality here. There are three things I want addressed before this can merge:

1. The addition of the `DECLINED` state. Maybe we should talk about this as a team.
2. Using a transaction in the repository
3. Is accepting included in this PR?

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        DECLINED;
Why are you adding a `DECLINED` state to a book? Can't only a request be "declined"?

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +     * DECLINED - Request has completed either by returning the book to the owner or request was declined
Previously I believe `ARCHIVED` was covering both the use case of "declined" and "archived". The disadvantage of this is that there is no nice way to show to a user that their request was declined b/c we can't differentiate between "archived" and "declined". However, if we add the `DECLINED` field here, we are going to be breaking logic across the app where this field isn't accounted for. I think we need to have a discussion before we add this field to the enum.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/res/layout/fragment_library_book_details.xml
> +                    android:visibility="@{viewModel.requesters.size() == 0? View.GONE: View.VISIBLE}"
Nice :+1:

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
Have you verified that the back button is still working correctly? I found the popUpTo stuff very un-intuitive when I was working with it.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +         Query query = mDb.collection(REQUESTS_COLLECTION).whereEqualTo(BOOK, bookID).whereNotEqualTo(STATE, Request.State.DECLINED);
You would still want to filter out `ARCHIVED` requests. Doesn't make sense to show requests on a book from a month ago for example.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +        mDb.collection(REQUESTS_COLLECTION).whereEqualTo("requester", requestedUID)
`"requester"` should be a constant.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo("book", bookRequestedID)
`"book"` should be a constant.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +//                        if(matchingRequests.size() != 1) {   // Uncomment when we can ensure user can't request same book twice
This is coming in my PR.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                                    .update("state", Status.DECLINED.name())
`"state"` should be a constant.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                                    .update("state", Status.DECLINED.name())
Also how come `.name()` instead of `.toString()`?

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                                            if (!request.getState().toString().equals(Status.DECLINED.name())) {
Again, how come `.name()`?

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                                                    .update("status", Status.AVAILABLE.name())
`"status"` should be a constant.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRequesterProfileFragment.java
> +        mBinding.declineRequest.setOnClickListener(v -> {
Are you not adding the accept button in this PR?

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +                request.setState(Request.State.DECLINED);
This doesn't make sense to me to mark a request as `DECLINED` when it was accepted and finished.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +    public void acceptSelectedRequester() {
Is this TODO?

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +     * Naviaates to a google map fragment to allow the selection of a location
Nit: Typo

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +     * Naviaates to a google map fragment to allow the selection of a location
Nit: Typo

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +                    mCurrentBook.setValue(book);
This feels hacky to me.

2020-11-19 17:33 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +    public void declineRequester(String requestedUID, String bookRequestedID, OnSuccessListener<? super Void> onDeclineSuccess, OnFailureListener onDeclineFailure, OnSuccessListener<? super Void> onS
I suggest you read about Firebase transactions (https://firebase.google.com/docs/firestore/manage-data/transactions)

That will make this function a lot nicer to read and also make sure this operation is atomic i.e. everything succeeds or nothing succeeds.

2020-11-19 17:57 UTC, cyrusdiego commented
@calebschoepp Accepting a request is **not** implemented in this PR, I'm implementing it in my PR as accepting a requester entails selecting a handoff location as well.

2020-11-19 18:28 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +    public void acceptSelectedRequester() {
finishing this off in my PR, had a sync with Taran yesterday regarding finishing the accept flow

2020-11-19 18:30 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
can this be turned into a lambda? kinda nit, but can make it a bit more compact

2020-11-19 18:30 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
same thing as prev comment, can this be turned into a lambda? kinda nit, but can make it a bit more compact

2020-11-19 18:33 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +    public void declineRequester(String requestedUID, String bookRequestedID, OnSuccessListener<? super Void> onDeclineSuccess, OnFailureListener onDeclineFailure, OnSuccessListener<? super Void> onS
I think if you define your own callback interface for the `addOnFailure`'s we can just pass in one callback function and reuse it for the different error cases. Looking at the lambda's you pass in, they're basically the same so you can just pass in the string you want to set the failure live event and the Log

2020-11-19 18:46 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        mDb.collection(REQUESTS_COLLECTION).whereEqualTo("book", bookRequestedID)
`"book"` should be constant

2020-11-19 20:32 UTC, calebschoepp commented
> @calebschoepp Accepting a request is **not** implemented in this PR, I'm implementing it in my PR as accepting a requester entails selecting a handoff location as well.

Okay that makes sense to me

2020-11-19 22:49 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        DECLINED;
Remove DECLINED from Book class

2020-11-19 22:49 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +     * DECLINED - Request has completed either by returning the book to the owner or request was declined
Replace DECLINED with ARCHIEVED

2020-11-19 23:00 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +                    mCurrentBook.setValue(book);
Keep hacky way for now; add comment in code

2020-11-20 02:54 UTC, armiantos reviewed
Left some comments that might improve this PR. Holding back on approving until changes requested by @calebschoepp are made. But awesome job implementing all this! I'm impressed. :rocket:

2020-11-20 02:54 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +     * DECLINED - Request has completed either by returning the book to the owner or request was declined
As of 19 November's discussion, we're keeping it as archived and will refactor in a separate PR if needed

2020-11-20 02:54 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo("book", bookRequestedID)
There's the `BOOKS_COLLECTION` constants that we can use so that we can easily update them in the future when necessary.

2020-11-20 02:54 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
Also might be nice to keep the variable names automatic, say `snapshots`

2020-11-20 02:54 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +    public void declineRequester(String requestedUID, String bookRequestedID, OnSuccessListener<? super Void> onDeclineSuccess, OnFailureListener onDeclineFailure, OnSuccessListener<? super Void> onS
If possible keep the failure listener to just 1. Since we know its a failure anyways we can just call it with different messages instead of having 5 callbacks as an argument just to call decline requester.

2020-11-21 05:16 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        DECLINED;
Done

2020-11-21 05:18 UTC, Taranjot-Singh commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
Verified.

2020-11-21 05:18 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +         Query query = mDb.collection(REQUESTS_COLLECTION).whereEqualTo(BOOK, bookID).whereNotEqualTo(STATE, Request.State.DECLINED);
Done

2020-11-21 05:22 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +                    mCurrentBook.setValue(book);
TODO: Need to add snapshot listener for mCurrentBook

2020-11-21 05:32 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
Done. Thank you Cyrus.

2020-11-21 06:23 UTC, armiantos reviewed
Left some comments to consider before merging this PR. Awesome work overall Taran! :1st_place_medal:

2020-11-21 06:23 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo(STATE_FIELD, Request.State.REQUESTED.name());
```suggestion
                .whereEqualTo(STATE_FIELD, Request.State.REQUESTED.toString());
```
According to [ref](https://dzone.com/articles/enum-using-the-name-and-tostring-methods-correctly) although .name() and toString() return essentially the same thing, use of `toString()` is encouraged and we're already using this everywhere else

2020-11-21 06:23 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    ArrayList<Request> matchingRequests = new ArrayList<>();
Can't we reuse the requestsOnBook array from above? It seems like we're just transferring it. We can do the error checks and do an early return. There's also another check for matching requests size != 1 which would never happen if we had this

2020-11-21 06:23 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
Do we need to specify/cast this lambda?

2020-11-21 06:23 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +
Nit new line

2020-11-21 06:23 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +    private User mSelectedRequester = new User();
Is there a reason we're initializing this early? I think null would be beneficial to check when this user would not be intiialized

2020-11-21 06:28 UTC, calebschoepp requested changes
I'm super impressed Taran. This PR has come a long way! Couple more things to address but we are almost there.

2020-11-21 06:28 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
>          Query query = mDb.collection(BOOKS_COLLECTION).whereEqualTo("owner", FirebaseAuth.getInstance().getUid());
`"owner"` should be a constant.

2020-11-21 06:28 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo(STATE_FIELD, Request.State.REQUESTED.name());
Does this mean the list won't show an accepted requester? What do we do in that case?

2020-11-21 06:28 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                                return;
Maybe you should call the `onDeclineFailure` callback before returning in all these instances? Not too sure on this.

2020-11-21 06:28 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        return;  // We don't show toast here to user. Can we do that (we don't have access to mFailureMsgEvent of ViewModel)?
You would call `onDeclineFailure` which could show toast.

2020-11-21 06:28 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        return;  // We don't show toast here to user. Can we do that (we don't have access to mFailureMsgEvent of ViewModel)?
See above.

2020-11-21 06:28 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    // TODO: Need to change mCurrentBook locally in viewmodel
Please make an issue for this.

2020-11-21 06:28 UTC, calebschoepp commented on app/src/main/res/layout/fragment_library_book_details.xml
> +                    android:visibility="@{viewModel.requesters.size() == 0? View.GONE: View.VISIBLE}"
Super nit: ...

```suggestion
                    android:visibility="@{viewModel.requesters.size() == 0 ? View.GONE: View.VISIBLE}"
```

2020-11-21 06:34 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    ArrayList<Request> matchingRequests = new ArrayList<>();
What is meant by "reusing requestsOnBook" array? 

The size != 1 happens if a user can request a book more than once. This was possible  when I started implementing this more PR but now I believe Caleb fixed that. Do you think it's not a useful sanity check?

2020-11-21 06:35 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
What does this mean?

2020-11-21 06:37 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo(STATE_FIELD, Request.State.REQUESTED.name());
name() would convert the enum to string exactly like the enum
toString() can be overridden and its behavior can be changed.
If we use toString() everywhere, we should be consistent. I'll update this

2020-11-21 06:43 UTC, armiantos reviewed
Replied comments

2020-11-21 06:43 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
```suggestion
                    mDb.runTransaction(transaction -> {
```
can we make do with the above?

2020-11-21 06:43 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    ArrayList<Request> matchingRequests = new ArrayList<>();
I think it's best to remove it to clean up the code. Scoping, assumptions and design are made in such way so that we don't have to write more code (and hence less error prone).

With this we can just query for non archived requests and have a single array that we iterate through instead of moving the data from `requestsOnBook` to `matchingRequests`

2020-11-21 06:43 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        if (updateBookStatus) {
We're also copying `allOtherRequestsAreArchived` and `updateBookStatus`. This way it's like both someone's telling me what to do and I'm asking someone what to do. I think choose one over the other is better.

2020-11-21 06:43 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo(STATE_FIELD, Request.State.REQUESTED.name());
Thanks!

2020-11-21 19:51 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo(STATE_FIELD, Request.State.REQUESTED.name());
Done

2020-11-21 19:53 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
I tried removing it; it causes an error ans red underlines the onSuccessListener. This is what it says:

Required type: OnSuccessListener <? super Object>
Provided: OnSuccessListener <capture of ? super Void>

Probably best to leave it in?

2020-11-21 19:53 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +
Resolved

2020-11-21 19:59 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +    private User mSelectedRequester = new User();
Removed the initialization; good catch!
Can you elaborate on the part where you say it would be useful to check if it is null or not. Why and where would that be useful? Can't of where that check would be useful.

2020-11-21 20:00 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
>          Query query = mDb.collection(BOOKS_COLLECTION).whereEqualTo("owner", FirebaseAuth.getInstance().getUid());
Done

2020-11-21 20:28 UTC, Taranjot-Singh commented on app/src/main/res/layout/fragment_library_book_details.xml
> +                    android:visibility="@{viewModel.requesters.size() == 0? View.GONE: View.VISIBLE}"
Done

2020-11-21 20:29 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    // TODO: Need to change mCurrentBook locally in viewmodel
Done

2020-11-21 20:58 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
That error seems unrelated to converting it to a lambda

2020-11-21 21:04 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
I believe it is already a lambda. I think Armi means removing the type-cast before the lambda parameter.

2020-11-21 21:06 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
Ah i see my bad, hmm regardless I'm not sure why you're getting that error. Ill try to take a look at your branch rn

2020-11-21 23:00 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .whereEqualTo(STATE_FIELD, Request.State.REQUESTED.name());
The query that was there previously was giving an error and so I changed it to this.

But after thinking about it, you are right and the previous query is what we want. After investigating, I figured out we needed a composite index to make the previous query work. So I've added that and reverted back to previous query in the latest changes I've pushed.

2020-11-21 23:04 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        return;  // We don't show toast here to user. Can we do that (we don't have access to mFailureMsgEvent of ViewModel)?
Had to pass a separate lambda to call here since we want a different behavior than onDeclineFailure.onFailure().

Here we want to re-navigate to the page and page will update to fix the error.

2020-11-21 23:05 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                                return;
Removed this piece of code altogether

2020-11-21 23:08 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        if (updateBookStatus) {
We can only access final or effectively final variables within the lambda function so we convert allOtherRequestsAreArchived to a final boolean variable. Thats why we have the "final boolean updateBookStatus = allOtherRequestsAreArchived". I've  now changed the name of updateBookStatus  to be finalAllOtherRequestsAreArchived so that it's more clear why we create this variable.

2020-11-22 00:58 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_library_book_details.xml
> +                    android:visibility="@{viewModel.showHandoffButton()? View.VISIBLE : View.GONE}"
nit: 
```suggestion
                    android:visibility="@{viewModel.showHandoffButton() ? View.VISIBLE : View.GONE}"
```

2020-11-22 00:58 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_library_book_details.xml
> +                    android:visibility="@{viewModel.requesters.size() == 0? View.GONE: View.VISIBLE}"
nit
```suggestion
                    android:visibility="@{viewModel.requesters.size() == 0 ? View.GONE: View.VISIBLE}"
```

2020-11-22 00:59 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_library_book_details.xml
> +                    android:visibility="@{viewModel.requesters.size() == 0? View.GONE: View.VISIBLE}"
err unless the formatter doesn't detect this then it's all good

2020-11-22 01:12 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +    private static final String BOOK_FIELD = "book";
these variables are already defined above. We can either use the ones already provided or use yours, doesn't matter to me

2020-11-22 02:36 UTC, calebschoepp reviewed
Yeah LGTM. Just resolve the others comments.

2020-11-22 02:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    mDb.runTransaction((Transaction.Function<Void>) transaction -> {
I don't think removing this cast is worth the effort right now.

2020-11-22 02:36 UTC, calebschoepp approved these changes

2020-11-22 02:49 UTC, armiantos approved these changes
Other than the nits it looks good to me. IMO, if you want to get the PR in first please do, just make sure to assign someone or yourself for the refactors/clean-ups (esp. for the redundant fields so that we don't confuse our TA.

2020-11-22 02:49 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +    private static final String BOOK_FIELD = "book";
Yes, I think we should use the _FIELD convention. It shouldn't be too bad of a refactor.

2020-11-22 02:49 UTC, armiantos commented on app/src/main/res/layout/fragment_library_book_details.xml
> +                    android:visibility="@{viewModel.requesters.size() == 0? View.GONE: View.VISIBLE}"
Formatter says it's good lol

2020-11-22 03:50 UTC, merged