WIP: Handoff Location
CMPUT301F20T24/Unlibrary pull request #121
Opened 2020-11-19 17:40 UTC by cyrusdiego

# Summary
- Integrated Maps and Places SDK to choose a handoff location 
- Select and accept a requester from the list of requesters for a book 

# Screenshots
- If you're working on UI

# TODO
PR is still WIP

- [ ]  Comments 

- [ ] Potentially put the logic for detailed book view into an inner class or it's own viewmodel 

- [ ] Accepted requester's profile page should not have a button on it anymore (assumption: owner cannot cancel an accepted request) 

Closes #50

2020-11-22 05:18 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +                .whereNotEqualTo("state", Request.State.DECLINED.toString());
This is unrelated to the main feature of this PR but I think this was missed from the recent merges so I just updated it to use the `DECLINED` state

2020-11-22 05:34 UTC, calebschoepp reviewed
Great stuff @cyrusdiego , I think this is close to ready to merge. Just a few questions and nits.

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +     * DECLINED - Request has completed either by returning the book to the owner or request was declined
How come we are switching this. Didn't we decide to keep it as `ARCHIVED`?

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
Have you tested back stack behaviour?

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
Why was this added?

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
For this and for all new navigation paths.

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +        mBinding.map.onCreate(savedInstanceState);
What is lite mode?

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +        googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(mViewModel.getAcceptedRequestLocation().getValue(), 12));
What is this hardcoded `12`? Maybe make it a constant with a meaningful name?

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        Request request = task.getResult().toObjects(Request.class).get(0);
Should we do a sanity check that there is one request? Probably not b/c we don't do stuff like that in other places of the app.

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +     * In this case, we just add a marker near Sydney, Australia.
This block comment feels a bit inaccurate in a few places.

2020-11-22 05:34 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +        googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(latLng, 10.0f));
Camera? Why for the maps?

2020-11-22 05:39 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +        googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(latLng, 10.0f));
the `CameraUpdateFactory` is basically just the "view" of the map itself. So that line will essentially move the "view" to that latlng with that zoom level (10.0f)

2020-11-22 05:41 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +        mBinding.map.onCreate(savedInstanceState);
Basically a less robust maps fragment. It only has a few features baked into it. It's primarily used if you only want to show a bitmap of a map. Especially useful if you want multiple maps in one page iirc.

2020-11-22 05:42 UTC, cyrusdiego commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
I have not tested this tbh. I think I more or less copied and pasted this part... With that, I think we can maybe create an issue to test navigation?

2020-11-22 05:44 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +        googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(mViewModel.getAcceptedRequestLocation().getValue(), 12));
The 12 is the zoom level of the map, I'll make it a constant.

2020-11-22 05:45 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        Request request = task.getResult().toObjects(Request.class).get(0);
I think to be pedantic it would be a good idea to do a check on the size before I index. At the time I think I kind of just figured it would be impossible, but can't hurt to have the check

2020-11-22 05:45 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +     * In this case, we just add a marker near Sydney, Australia.
Whoops, a remnant from copying example code, will update this

2020-11-22 05:49 UTC, cyrusdiego commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
I think that was a mistake on my part. When I was hooking up the navigation I noticed there wasn't a `popUpTo` and `popUpToInclusive` field and thought we needed one. Looking at it now we wouldn't want this. Removing it

2020-11-22 05:50 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +     * DECLINED - Request has completed either by returning the book to the owner or request was declined
Missed this when I was rebasing, changing it back to `ARCHIVED`

2020-11-22 06:01 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        Request request = task.getResult().toObjects(Request.class).get(0);
actually... I think this can be put off for a refactor PR so that we can tackle all the places we do something similar, what do you think? I don't mind doing a check now.

2020-11-22 06:07 UTC, calebschoepp submitted a review, later dismissed

2020-11-22 06:07 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +        mBinding.map.onCreate(savedInstanceState);
Cool

2020-11-22 06:08 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +        googleMap.moveCamera(CameraUpdateFactory.newLatLngZoom(latLng, 10.0f));
Oh I see, "view" is a good metaphor.

2020-11-22 06:09 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        Request request = task.getResult().toObjects(Request.class).get(0);
Maybe just throw in the check now? Who knows if we will get around to that refactor. Either way not a huge deal to me.

2020-11-22 06:10 UTC, calebschoepp commented on app/src/main/res/navigation/nav_graph.xml
> +            app:popUpToInclusive="true" />
I would prefer you do a quick sanity check that the backstack works as you expect it to with your new screens while it is fresh in your mind.

2020-11-22 06:32 UTC, Taranjot-Singh requested changes
Thank you Cyrus for this! Lots of great work!

Just noticed a problem: 
The queries in acceptRequester() and updateHandoffLocation() and fetchHandoffLocation() will need to be updated to filter out ARCHIVED requestes.For eg., currently in acceptRequester(), we get all requests associated to the book. Then from those requests we change the status of all requests to either accepted (if the requester matches selected requester) or archived (if requester does not match selected requester).  This means that previously archived requests by the same requester will be marked accepted leading to multiple requests that are accepted on the same book. And this also means that we will unnecessarily go through  some archived requests on the book and change their state to ARCHIVED again

2020-11-22 06:40 UTC, calebschoepp commented
@cyrusdiego thanks for addressing the back stack issues. All good on my end but I agree with Taran's observation so will hold off on an approval.

2020-11-22 07:27 UTC, calebschoepp approved these changes
LGTM!

2020-11-22 07:47 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                            if (acceptedRequestDocument != null) {
If acceptedRequestDocument is null, we do not want to continue on the code that is after this if statement. I.e. If we find no request to accept, we should not decline other requests.

I think we should do the opposite check where if acceptedRequestDocument == null, we log and return.

2020-11-22 07:48 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                            // Firestore transactions do not allow writes to occur after a read
I think you meant to say the opposite? We can't do any reads after writes.

2020-11-22 08:09 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                            if (acceptedRequestDocument != null) {
I we need something like
```suggestion
                            if (acceptedRequestDocument == null) {
                                onFailureListener.onFailure(new Exception("The request to accept wasn't found"));
                                return;
                            }
```

2020-11-22 08:15 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                            onFailureListener.onFailure(new Exception("Error updating handoff location"));
Nit: I would make the log string more descriptive so we can differentiate it from other types of error that may occur during update.

Something like 
```suggestion
                            onFailureListener.onFailure(new Exception("Unexpected number of requests returned during update.  " + requests.size() + " requests found."));
```

2020-11-22 08:17 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                            onFailureListener.onFailure(new Exception("Error fetching handoff location"));
Same Nit: A more descriptive error string would be nice.

```suggestion
                            onFailureListener.onFailure(new Exception("Unexpected number of requests returned when fetching location.  " + requests.size() + " requests found."));
```

2020-11-22 08:19 UTC, Taranjot-Singh reviewed
I can't wait for this PR to be merged :D
 This will tie so many things together. 

One change that is necessary ( changing the acceptedRequestDocument == null check). And the rest are a few nits.

2020-11-22 17:40 UTC, armiantos requested changes
Awesome work @cyrusdiego! Just left a few nits to consider before merging. Looks good otherwise.

2020-11-22 17:40 UTC, armiantos commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET" /> <!-- Prevent need to display in app that camera is unavailable -->
Is the comment better split? since the camera comment isn't related to the internet permission

2020-11-22 17:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +
Nit: double new lines

2020-11-22 17:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        }).addOnSuccessListener(onSuccessListener).addOnFailureListener(onFailureListener);
Maybe splitt to 2 lines (one for each `.addOn*`

2020-11-22 17:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    if (requestTask.isSuccessful()) {
An early return could make the code less 'nested'

2020-11-22 17:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +        mLibraryRepository.fetchHandoffLocation(mCurrentBookRequesters.getValue().get(0).getUID(), mCurrentBook.getValue().getId(),
Is the accepted one always the first one?

2020-11-22 17:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +
Nit: new line

2020-11-22 17:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +        mBinding = FragmentMapsBinding.inflate(inflater, container, false);
Do we not need to call `.setLifecycleOwner` on `mBinding`?

2020-11-22 17:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +     * Accepts the selected requester and sets the handoff location
```suggestion
     * Accepts the selected requester and sets the handoff location
     *
     * @param lating - location for handoff given by its latitude longitude coordinates     
```

2020-11-22 17:42 UTC, armiantos reviewed
I think I figured out one of my own comments but please lmk if I'm interpreting something wrong. Thank you!

2020-11-22 17:42 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +        mLibraryRepository.fetchHandoffLocation(mCurrentBookRequesters.getValue().get(0).getUID(), mCurrentBook.getValue().getId(),
Ah I think I get it but just to confirm, `mCurrentBookRequesters` will have size 1 because everyone else is archived and because of the `snapshotListener`?

2020-11-22 22:32 UTC, cyrusdiego commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET" /> <!-- Prevent need to display in app that camera is unavailable -->
formatting issue, fixing now

2020-11-22 22:39 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +        mLibraryRepository.fetchHandoffLocation(mCurrentBookRequesters.getValue().get(0).getUID(), mCurrentBook.getValue().getId(),
Yeah, so this function will only be ran if the status is `ACCEPTED` and if there's only 1 user in `mCurrentBookRequesters`. If it's in the `ACCEPTED` state then by design, the `mCurrentBookRequesters` will only have the one book requester (the accepted requester) in the list

2020-11-22 22:40 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/MapsFragment.java
> +        mBinding = FragmentMapsBinding.inflate(inflater, container, false);
yep, forgot to put that

2020-11-22 23:00 UTC, armiantos reviewed
One last check!

2020-11-22 23:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +            if (s) {
Is this also supposed to be if s != null?

2020-11-22 23:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .addOnCompleteListener(task -> {
Since we have an onfailurelistener at the bottom should this be addonsuccesslistener? i think the original heuristic was if you need a task that's done both on failure or success, we use add oncompletelistener. [Difference between isSuccessful() and isComplete() method](https://stackoverflow.com/questions/48275458/difference-between-issuccessful-and-iscomplete-method)

2020-11-22 23:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +        mLibraryRepository.fetchHandoffLocation(mCurrentBookRequesters.getValue().get(0).getUID(), mCurrentBook.getValue().getId(),
Sweet!

2020-11-22 23:04 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .addOnCompleteListener(task -> {
The other option would be to call the onFailureListener in the else block of the if(task.isSuccessful())

2020-11-22 23:06 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +            if (s) {
isn't `if (s)` the same as `if (s != null)` ?

2020-11-22 23:06 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +            if (s) {
i could just be in Python world lol

2020-11-22 23:09 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .addOnCompleteListener(task -> {
If we modify this @armiantos then it would make sense to modify updateHandoffLocation() and acceptRequester() as well to have either the onSuccess and onFailure Listener or the onCompleteListener() with the if-else block.

2020-11-22 23:09 UTC, Taranjot-Singh commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        if (acceptedRequestDocument != null) {
This should be if (acceptedRequestDocument **==** null)  [not the **!=**]

2020-11-22 23:15 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        if (acceptedRequestDocument != null) {
my bad, i moved the the logic over but forgot to change the predicate :')

2020-11-22 23:49 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +            if (s) {
> Python world

lmao

2020-11-22 23:54 UTC, Taranjot-Singh approved these changes

2020-11-23 00:10 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
> +            if (s) {
S here is a boolean while s in the bottom is different gotcha

2020-11-23 00:10 UTC, armiantos approved these changes
Approved! Thank you for implementing this. This is a huge feature in such little code.

2020-11-23 00:11 UTC, Taranjot-Singh approved these changes
Thank you! Great work!!

2020-11-23 00:12 UTC, merged