added exchange and marketplace search UML
CMPUT301F20T24/Unlibrary pull request #22
Opened 2020-10-14 04:20 UTC by ghassanzadeh

Added some classes for Exchange activities and Search in the MarketPlace that i thought is missing in our UML. I am not sure how much details i need to add to each class. Please let me know if i need to change any part and if the relationships make any sense! Thanks team :)

2020-10-14 05:10 UTC, ghassanzadeh commented
![Unlibrary_UML](https://user-images.githubusercontent.com/43598866/95946172-3e40cb80-0da9-11eb-881b-e0a69250bc89.png)

2020-10-14 05:13 UTC, calebschoepp approved these changes
LGTM! Great work.

2020-10-14 05:22 UTC, cyrusdiego requested changes
Left some comments, I think for each path (library, unlibrary, marketplace, profile) we'd have separate viewmodels and repositories. So for the marketplace, we wouldn't want to use the libraries viewmodel as it would only house the books the owner has. For the marketplace we want a viewmodel and repository combo that holds all the books available to be borrowed.

2020-10-14 05:22 UTC, cyrusdiego commented on doc/p1-uml.txt
> +BorrowActivity --o CameraService
I think the aggregation here is the opposite of what we'd want. The Camera Service would be a part of the BorrowActivity.

2020-10-14 05:22 UTC, cyrusdiego commented on doc/p1-uml.txt
> +SearchMarketPlace o-- LibraryViewModel
I think for the MarketPlace Activity, we'd actually want to use a separate ViewModel and Repository, not the one from the Library

2020-10-14 05:22 UTC, cyrusdiego commented on doc/p1-uml.txt
> +    -acceptRequest()
I think accepting / declining requests would only be under the library activity. I'm assuming this Borrow activity is when you click on a book to request to book, so then we'd only have a request method.

2020-10-14 17:29 UTC, armiantos reviewed
Just nits to make the UML more readable. Great job!

2020-10-14 17:29 UTC, armiantos commented on doc/p1-uml.txt
> +class SearchMarketPlace{
I would rename this to `MarketPlaceViewModel` and create a `MarketplaceActivity` that uses this so it's uniform with `LibraryActivity` and `ProfileActivity`

2020-10-14 17:29 UTC, armiantos commented on doc/p1-uml.txt
> +BorrowActivity --o CameraService
The borrow activity is a great idea!

2020-10-14 22:47 UTC, cyrusdiego requested changes

2020-10-14 22:47 UTC, cyrusdiego commented on doc/p1-uml.txt
> +ExchangeActivity --o ExchangeViewModel
aggregation is backwards

2020-10-14 23:15 UTC, armiantos approved these changes
Looks good to me!

2020-10-15 00:11 UTC, cyrusdiego approved these changes

2020-10-15 03:32 UTC, merged