Integrate Firebase Authentication
CMPUT301F20T24/Unlibrary pull request #30
Opened 2020-10-16 07:34 UTC by calebschoepp

## Summary
After a lot more time figuring out 2-way binding than I care to admit, I've added basic authentication to our app! There's two key parts to the changes. First, the auth activity. Second, the authenticated activity.

The `AuthActivity` is pretty straightforward. It really is just a login screen and a register screen that both hook into Firebase Auth. I wired it up to bring you to a logout button just to test the functionality.

The `AuthenticatedActivity` is the cool bit. Every activity (except `AuthActivity` b/c of infinite recursion reasons :tongue: ) extends it. In short what it does is redirect to the login screen if the user is not logged in. This means that any possible entry point to our app will be secure (launcher, notification, etc.). Please ask any questions you have about this architecture.

## Changes
- Rename a bunch of things. See below.
- Implement login, register, and an example logout
- Implement an abstract activity to lock everything behind authentication (basically a middle-ware)
- Remove actionbar
- Update to use Java 8 to let us use lambdas
- Added a `SingleLiveEvent` class. PLEASE QUESTIONS ABOUT THIS, b/c it is a super valuable pattern.
- The UI is a work in progress

## Open Questions
- Is everyone okay with the renaming I did?
    - Sign In -> Login (Feels simpler to me)
    - Sign Up -> Create Account / Register (Feels simpler to me)
    - `LoginActivity` -> `AuthActivity` (Feels more accurate to me)
- People okay with me bumping to Java 8 for lambdas?
- I didn't collect first name and last name b/c we are short on screen space and I don't think it is actually in the requirements. This okay?

## TODO
- Build out the logic to connect a `FirebaseUser` to our custom Firestore `User` entity.
- Test `AuthViewModel`
- A number of TODOs littered throughout my changes

2020-10-16 16:43 UTC, cyrusdiego requested changes
Added some comments throughout, overall it looks good to me :D Aside from the general comments should also have documentation (Javadoc style) and unit tests (if/where applicable)

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +            mEmail = new MutableLiveData<String>();
Nit: Can replace `<String>` with `<>` (From Android IDE: Explicit type argument String can be replaced with <> ), same for all getters below

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +    private MutableLiveData<String> mEmail = new MutableLiveData<>();
Is it necessary to initialize these MutableLiveData variables here if you do so in the getters?

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +        if (mEmail.getValue() == null || mEmail.getValue().isEmpty()) {
Would probably want to set up thorough validation of email (missing '@', invalid email address, etc.) . Maybe it's something that can be done in Firebase Auth side rather than doing say Regex here.

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +        if (mEmail.getValue() == null || mEmail.getValue().isEmpty()) {
Also, Material's EditText has built in "error" messages. I think those would be better at showing an invalid value passed instead of Toasts. [Link](https://material.io/develop/android/components/text-fields) (Skip to "Adding errors to a text field")

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_login.xml
> +                    android:hint="Email">
Move hardcoded strings to the string resource file

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_login.xml
> +                    android:hint="Password"
Move hardcoded strings to the string resource file

2020-10-16 16:43 UTC, cyrusdiego commented on .github/workflows/main.yml
> +        continue-on-error: true
Should this change be in this PR? I thought this was already merged into master with your test PR

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +    public void register() {
Look at comments for the login() function, applies here as well

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/util/SingleLiveEvent.java
> +// https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/app/src/main/java/no/nordicsemi/android/blinky/viewmodels/SingleLiveEvent.java
In terms of citing, is this enough? Do we have to put in like licensing, date, etc? Not sure how nitpicky they'll be but I think I remember the prof talking about citing code in Assignment 1

2020-10-16 16:43 UTC, cyrusdiego commented on app/src/main/res/layout/activity_profile.xml
> +        android:text="Logout"
This is just a placeholder for now so up to you but could move the hardcoded string to the string resource file if you want.

2020-10-16 16:47 UTC, cyrusdiego commented
>Is everyone okay with the renaming I did?
Sign In -> Login (Feels simpler to me)
Sign Up -> Create Account / Register (Feels simpler to me)
LoginActivity -> AuthActivity (Feels more accurate to me)

I think the renames are good, a lot clearer tbh

> People okay with me bumping to Java 8 for lambdas?

I'm good with it, lol was going to bump it to Java 8 myself to use lambdas 

> I didn't collect first name and last name b/c we are short on screen space and I don't think it is actually in the requirements. This okay?

Should be fine, would be a fairly simple fix if the spec's change to require first and last name

2020-10-16 17:38 UTC, calebschoepp commented on .github/workflows/main.yml
> +        continue-on-error: true
This is only here because I hadn't rebased to master yet. This is now resolved.

2020-10-16 17:39 UTC, calebschoepp commented on app/src/main/res/layout/activity_profile.xml
> +        android:text="Logout"
Just going to leave it hardcoded. Don't want us to forget about the string resource if we no longer need it.

2020-10-16 17:40 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/util/SingleLiveEvent.java
> +// https://github.com/NordicSemiconductor/Android-nRF-Blinky/blob/master/app/src/main/java/no/nordicsemi/android/blinky/viewmodels/SingleLiveEvent.java
Yeah I'm not sure. This sounds like a bigger conversation we need to have as a team about how we want do citations. For now, this link will be enough to get us back to the info we might need. I'll add a TODO as a reminder.

2020-10-16 17:46 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +    private MutableLiveData<String> mEmail = new MutableLiveData<>();
Good question. You're right that they get initialized in the getters. However, I still initialize them here because it is possible that the user clicks a button before the get function is called and it would throw a null exception error when trying to validate the data. Pre-initializing them here avoids that.

2020-10-16 17:51 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +    private MutableLiveData<String> mEmail = new MutableLiveData<>();
Ah makes sense, thanks for clarifying.

2020-10-16 17:52 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +    private MutableLiveData<String> mEmail = new MutableLiveData<>();
No problem. This is one of the things I was struggling with for so long :rofl:

2020-10-16 17:54 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +        if (mEmail.getValue() == null || mEmail.getValue().isEmpty()) {
Agreed that more validation is needed. Couple things:
- I tested registering with an invalid email and firebase stops it, but it would be nice to detect it client side and let the user know in advance
- Validation also needs to be added to things like the username (globally unique, no spaces, no crazy unicode crap, etc.)
- IMO this is outside the scope of this PR. Since this PR is already big is it okay if I file a ticket and include this validation in a follow-up PR?

2020-10-16 17:55 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +        if (mEmail.getValue() == null || mEmail.getValue().isEmpty()) {
Re: Error messages

I agree that text field errors is a better idea. I'll work on that. You fine if I still show `Invalid username or password.`  in a toast since it applies to both fields?

2020-10-16 18:06 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +        if (mEmail.getValue() == null || mEmail.getValue().isEmpty()) {
Re: validation
I agree it should be in a separate PR, now that you point out more details and now that I think about it, it'll be a decent amount of work to add logic on the client side. Yeah if you can just file another ticket for it, thanks!

Re: Error Messages
Yeah that should be fine to show those in a toast.

2020-10-16 18:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +    public void register() {
Resolving because we've addressed these concerns on `login()` thread.

2020-10-16 18:23 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +        if (mEmail.getValue() == null || mEmail.getValue().isEmpty()) {
Re: Error Messages

Now that I'm looking at the implementation for this too, I'm wondering if I could push it out of this PR and into my follow-up PR where I add validation. The errors are tightly coupled to the validation and it would also be nice if the errors were live with the text input. You alright if I punt this to the ticket I filed and add it in a follow-up PR?

2020-10-16 18:28 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +        if (mEmail.getValue() == null || mEmail.getValue().isEmpty()) {
Yeah that's fine by me :)

2020-10-16 18:35 UTC, cyrusdiego reviewed
Recent changes looks good! 
Can probably add the Javadoc comments in this PR but not sure if we'd want to have a separate PR to actually generate the HTML Javadoc? Up to you.

2020-10-16 18:38 UTC, calebschoepp commented
> Can probably add the Javadoc comments in this PR but not sure if we'd want to have a separate PR to actually generate the HTML Javadoc? Up to you.

Yep working on adding the comments rn. Probably won't bother with generating the docs. We can do that closer to the deadline or perhaps set it up as a step in our CI/CD.

2020-10-17 06:36 UTC, calebschoepp commented
@cyrusdiego I've finished adding docs and unit tests. Just looking for the LGTM :)

2020-10-17 19:16 UTC, cyrusdiego requested changes
Regarding documentation, I'm looking at the Javadoc lab slides ([link](https://eclass.srv.ualberta.ca/pluginfile.php/6121307/mod_resource/content/0/Code%20Conventions%20%20Javadoc%20%28Schoepp%29.pdf)) that were posted for the standards we'd have to follow. I think for the most part, all that's missing are the "Beginning Comments" at the top of each source file: 
![image](https://user-images.githubusercontent.com/32345990/96351581-9150a200-1079-11eb-9c6a-74eb96a4d7e9.png)

Sorry for being nitpicky with this D: I just read through the slides from the lab and I'm worried they're gonna be nitpicky with documenting and such.

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/EntryActivity.java
> +public class EntryActivity extends AuthenticatedActivity {
Missing class documentation

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/EntryActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
missing method documentation

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/EntryActivity.java
> +package com.example.unlibrary;
Missing source file header

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthActivity.java
> +package com.example.unlibrary.auth;
Missing source file header

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
> +package com.example.unlibrary.auth;
Missing source file header

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/LoginFragment.java
> +package com.example.unlibrary.auth;
Missing source file header

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/auth/RegisterFragment.java
> +package com.example.unlibrary.auth;
Missing source file header

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/util/AuthenticatedActivity.java
> +package com.example.unlibrary.util;
Missing source file header

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/util/SingleLiveEvent.java
> +package com.example.unlibrary.util;
Missing source file header, can probably put citation in here too

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/util/SingleLiveEvent.java
> +    public void observe(@NonNull final LifecycleOwner owner, @NonNull final Observer<? super T> observer) {
missing method documentation

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/util/SingleLiveEvent.java
> +    public void setValue(@Nullable final T t) {
missing method documentation

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/test/java/com/example/unlibrary/auth/AuthViewModelTest.java
> +package com.example.unlibrary.auth;
Missing source file header

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/test/java/com/example/unlibrary/auth/AuthViewModelTest.java
> +public class AuthViewModelTest {
I think for documenting the tests we don't need method comments but maybe put in a class comment? I'll leave this one up to you though, I didn't document my test for the recent lab so I'm not sure if we absolutely need to document unit test

2020-10-17 19:16 UTC, cyrusdiego commented on app/src/test/java/com/example/unlibrary/helper/LiveDataTestUtil.java
> +package com.example.unlibrary.helper;
Missing source file header, can put citation here

2020-10-17 19:44 UTC, calebschoepp commented
Hey no, I like a thorough review. I originally left them out because I thought the TA said we didn't need them, but I think you're actually right. I'll go back and add them after today, I'm currently busy.

2020-10-18 06:13 UTC, calebschoepp commented on app/src/test/java/com/example/unlibrary/auth/AuthViewModelTest.java
> +public class AuthViewModelTest {
Yeah, probably adequate just to add a class level comment describing what it tests.

2020-10-18 06:14 UTC, calebschoepp commented on app/src/test/java/com/example/unlibrary/helper/LiveDataTestUtil.java
> +package com.example.unlibrary.helper;
Will leave citation where it is at rn b/c we need to decide on a their formatting.

2020-10-18 06:19 UTC, calebschoepp commented
@cyrusdiego I have addressed all of your comments. Once again, don't worry about all the nits. Hopefully, this PR can serve as a goal post for all of the standards we want to enforce in our code.

I left the copyright/licenses as TODOs b/c IMO the team needs to have a discussion about formatting for this and I'd like to merge this behemoth PR sooner than later to minimize merge conflict headaches for other teamates.

2020-10-18 18:02 UTC, cyrusdiego approved these changes
LGTM! Thanks for working on this and doing all the documentation and unit tests :D

2020-10-18 20:06 UTC, merged

2020-10-23 02:52 UTC, armiantos commented
Closes #32