Add basic entity classes
CMPUT301F20T24/Unlibrary pull request #41
Opened 2020-10-20 05:52 UTC by armiantos

# Summary
- Empty constructors are needed for Firestore
- Every attribute needs a getter for Firestore
- Add Book, User, Request entities as specified in #19 

## To complete this PR
- Verify that Pair<Double, Double> lat lon can be stored in Firestore
- Add basic rules in Firestore so that only authenticated users can read data and users can only modify their own user information
- Link Firebase ID with mId in User class
- Check if uuid can be generated by Firestore
- Check if we can add a reference type in Firestore in custom objects (User, Request, Book)
- Finish javadocs

# TODO
- Link with repository

2020-10-20 18:24 UTC, calebschoepp requested changes

2020-10-20 18:24 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
>      private String mDescription;
It was my understanding that we weren't keeping `description` around as a field. Rather, description is the union of `Isbn` and `Title` and `Author`. Same goes for setters and getters on this field.

@cyrusdiego can you confirm?

2020-10-20 18:24 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
>      public Book(String isbn, String title) {
How come you only included these two fields in the constructor?

2020-10-20 18:24 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +    }
Noticed you removed the `archived` state. Without this state, how will we represent requests that are associated with a book that are no longer valid?

2020-10-20 18:27 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
>      public Book(String isbn, String title) {
These were from last time, I haven't updated Book entity other than the empty constructor and reformatting. I'll get to them today. Thanks for noting this though :)

2020-10-20 18:29 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +    }
I was thinking of marking it back to available, but now that I read it, a request with state available doesn't really make sense. Should I rename AVAILABLE to ARCHIVED then?

2020-10-20 18:30 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
>      private String mDescription;
That means one less thing to worry about. Sounds good to me, we can always add descriptions later.

2020-10-21 00:39 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +    }
Not sure what AVAILABLE is representing. ARCHIVED is relevant in the scenario where a user requests a book, is then accepted or declined (doesn't matter), and then the transaction is over and the request is no longer valid. Happy to hop on a call and hash this out b/c this is the part of the design I'm least confident in.

2020-10-21 02:13 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +    }
Yea no no I think this was me blanking out last night. Thanks for the catch Caleb :+1:

2020-10-21 18:45 UTC, calebschoepp commented
@armiantos let me know when you are ready for another pass on this.

2020-10-21 20:39 UTC, armiantos commented
Should be good for review, but I'll integrate with Firestore today as well (hopefully not too many changes in code).

2020-10-21 21:29 UTC, calebschoepp requested changes
@armiantos we're getting real close. Just a couple comments.

2020-10-21 21:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +     * ARCHIVED - Borrower has returned the book back to the owner and the borrow request is complete
ARCHIVED is also the terminal state for a DECLINED request once the requester has acknowledged it.

2020-10-21 21:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/User.java
> +package com.example.unlibrary.models;
File header comment needed.

2020-10-21 21:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/User.java
> +    private String mPhone;
I know this was in my schema RFC but the auth screen isn't currently collecting this (nor does it really have room to). Since it is not in the requirements to have to contact infos (email & phone) I would opt to just remove this attribute. We can always add it back later.

2020-10-21 21:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +package com.example.unlibrary.models;
File header comment needed.

2020-10-21 21:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
File header comment needed.

2020-10-21 21:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
>          mBooks = new ArrayList<>();
File header comment needed.

2020-10-21 21:51 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +     * ARCHIVED - Borrower has returned the book back to the owner and the borrow request is complete
Ah right we can merge them together, thanks!

2020-10-21 21:53 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/User.java
> +    private String mPhone;
Sounds good. Removing it.

2020-10-21 22:13 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +    }
Wait don't we need to display a declined state? How would we decide when to display declined vs hide it from the user? @calebschoepp

2020-10-21 22:17 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Request.java
> +package com.example.unlibrary.models;
Added

2020-10-21 22:17 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
Added

2020-10-21 22:17 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
>          mBooks = new ArrayList<>();
Added

2020-10-21 22:25 UTC, cyrusdiego reviewed
Left a comment, looks good otherwise :D

2020-10-21 22:25 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +import java.util.List;
Nit: I think this import is unused

2020-10-21 22:26 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +import java.util.List;
Ah thank you for catching this. I was debating whether to use List over ArrayList to make it more generic.

2020-10-21 22:26 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/User.java
> +package com.example.unlibrary.models;
Added

2020-10-21 22:43 UTC, calebschoepp commented
Yeah you have a LGTM from me as well once my comments are resolved.

2020-10-21 23:25 UTC, armiantos commented
I decided to push some of the _TODO to complete this PR_ to future TODOs so that people that depend on the models defined here can get started. I will verify and make changes in another PR to ensure that these models can be used in Firestore.

2020-10-22 01:42 UTC, calebschoepp approved these changes
LGTM!

2020-10-22 01:56 UTC, merged

2020-10-23 02:50 UTC, armiantos commented
Closes #33