Taran golnoush/fragment library book ui
CMPUT301F20T24/Unlibrary pull request #42
Opened 2020-10-21 18:22 UTC by ghassanzadeh

Hi everyone,
Added the .xml file for the cardview as i posted the photo on the discord.

Thanks

2020-10-21 18:25 UTC, ghassanzadeh commented
i need to modify the id parts since we don't use findviewbyid().

2020-10-21 18:49 UTC, calebschoepp requested changes
Great work guys. Left a couple of comments

2020-10-21 18:49 UTC, calebschoepp commented on app/src/main/res/drawable/status_color.xml
> +        android:color="#4CAF50"/>
Pretty sure there is a `colors.xml` file that `#4CAF50` can be extracted to as a resource e.g. name it something like `green`

2020-10-21 18:49 UTC, calebschoepp commented on app/src/main/res/layout/fragment_library_book.xml
> +    app:cardElevation="5dp">
IMO we should extract this as a standard style resource in `styles.xml` and use it for every card in the app.

Thoughts @cyrusdiego ?

2020-10-21 18:49 UTC, calebschoepp commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:textAppearance="?android:textAppearanceMedium"
Just curious, what does the `?` indicate?

2020-10-21 18:49 UTC, calebschoepp commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:id="@+id/bookAuthor"
Are we standardizing on camelCase or snake_case for ids @cyrusdiego @armiantos ?

2020-10-21 18:53 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_library_book.xml
> +    app:cardElevation="5dp">
Yeah, I think extracting these properties to a common style is a good idea, we would most likely have 3 types of "cards" (library, unlibrary, and exchange) and they may all have this common style.

2020-10-21 18:54 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:id="@+id/bookAuthor"
I think snake_case. By default, android studios use snake_case for ids, strings, etc.

2020-10-21 19:00 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:textColor="@android:color/black"
I think these can be extracted to the style.xml as well or material UI may have default values we can just use with their theming?

2020-10-21 19:00 UTC, cyrusdiego requested changes
Good job guys, left some comments as well.

2020-10-21 19:03 UTC, ghassanzadeh commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:textAppearance="?android:textAppearanceMedium"
that's just the syntax to use textAppearance. We can use textsize too.

2020-10-21 19:04 UTC, ghassanzadeh commented
Thanks @cyrusdiego and @calebschoepp, will modify the file with these feedbacks.

2020-10-21 19:38 UTC, armiantos commented on app/src/main/res/layout/fragment_library_book.xml
> +    app:cardElevation="5dp">
Either way, the margins could've been simplified to `android:layout_margin` I believe.

2020-10-21 21:34 UTC, armiantos commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:textAppearance="?android:textAppearanceMedium"
? indicates you want to use style, aka `@android:style` I believe

2020-10-21 21:49 UTC, armiantos requested changes
Other than the small nitpicks, it looks good guys!

2020-10-21 21:49 UTC, armiantos commented on app/src/main/res/layout/fragment_library_book.xml
> +            android:layout_weight="2">
```suggestion
            android:layout_weight="2"
            android:layout_gravity="center">
```
to center the picture in the layout

2020-10-21 21:49 UTC, armiantos commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:text="Title"
```suggestion
                android:text="@{book.title}"
```
To get everyone familiar with data binding

2020-10-22 04:42 UTC, armiantos commented on app/src/main/res/layout/fragment_library_book.xml
> +                android:text="Title"
You can use `@{book.author}` too now

2020-10-22 19:57 UTC, armiantos commented
Closes #31

2020-10-26 03:29 UTC, ghassanzadeh commented
close #42

2020-10-26 03:32 UTC, closed without merging

2020-10-26 03:32 UTC, ghassanzadeh commented
Closes #42