Added example repository
CMPUT301F20T24/Unlibrary pull request #43
Opened 2020-10-22 01:17 UTC by drojasca

# Summary
- Created example repository for the library view
- Connected LiveData with the Library fragment so that any changes in the database are reflected in the UI

# Todo
- Documentation
- Add create, modify, and delete functions in the repository 
- General code clean up
- Change entry activity back to EntryActivity

2020-10-22 19:48 UTC, armiantos requested changes
Great job! Architecture wise looks really clean. Remember to run format before merging this PR. 

Current limitations are:
- Books are currently being identified using its ISBN
- Data to firestore is currently still being done using HashMap, this'll be a custom object in an upcoming PR
- Adapter is being reset on every data update, might save resources if we call `adapter.notifySetDatasetHasChanged()` instead

2020-10-22 19:48 UTC, armiantos commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-firestore:21.7.1'
Because we have `com.google.firebase:firebase-bom:25.12.0` we don't need to specify version. Following Google's best practices, it's best to use the following instead
```suggestion
    implementation 'com.google.firebase:firebase-firestore'
```
[ref](https://firebase.google.com/docs/firestore/quickstart)

2020-10-22 19:48 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +     * Bind ViewModel to fragment when fragment is created.
Should this be an inline comment instead of being in the javadocs since it's a lifecycle method?

2020-10-22 19:48 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +    private Observer<ArrayList<Book>> bookListObserver;
Let's follow best Android code convention best practices. Private variables should be prefixed with m.
```suggestion
    private Observer<ArrayList<Book>> mBookListObserver;
```

2020-10-22 19:48 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +        });
Do we need to reset the adapter or can we get away with calling `adapter.notifyDatasetHasChanged()`?

2020-10-22 19:48 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +    private LibraryRepository libraryRepository;
```suggestion
    private LibraryRepository mLibraryRepository;
```
same here for private variables

2020-10-22 19:48 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +        });
Could also be a lambda to make it cleaner

2020-10-23 01:41 UTC, drojasca commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +        });
I changed the observer to use a lambda function instead and changed it so that the notifyDatasetHasChanged() inside the adapter.

2020-10-23 01:47 UTC, cyrusdiego requested changes
Couple of nits but overall looks great!

2020-10-23 01:47 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +/*
Nit: file header should be at top of file, above imports

2020-10-23 01:47 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +
Nit: extra line

2020-10-23 01:47 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> + * LibraryRepository
Nit: file header should be at top of file, above imports

2020-10-23 01:47 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +        registration = query.addSnapshotListener(new EventListener<QuerySnapshot>() {
Could this be replaced by a lambda? May be cleaner as opposed to an anon class

2020-10-23 01:47 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +/*
Nit: file header should be at top of file, above imports

2020-10-23 01:47 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +     * @param owner  unique user identifier of the owner of the book
Nit: extra space

2020-10-23 01:57 UTC, drojasca commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +        registration = query.addSnapshotListener(new EventListener<QuerySnapshot>() {
I don't think that you are able to replace it with a lambda, and the android documentation does it this way as well, I think this is the best way.

2020-10-23 02:07 UTC, cyrusdiego submitted a review, later dismissed
LGTM :)

2020-10-23 02:08 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryBooksFragment.java
> +        });
Noice

2020-10-23 02:11 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    .addOnSuccessListener(new OnSuccessListener<Void>() {
Nit: Can you make these all lambdas?

2020-10-23 02:12 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    .addOnFailureListener(new OnFailureListener() {
Nit: Same here

2020-10-23 02:12 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                .addOnSuccessListener(new OnSuccessListener<Void>() {
etc.

2020-10-23 02:17 UTC, armiantos requested changes
A few more nits that you can auto commit through Github.

2020-10-23 02:17 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
> +import androidx.lifecycle.Transformations;
```suggestion
```
unused import

2020-10-23 02:17 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +        });
```suggestion
        registration = query.addSnapshotListener((value, error) -> {
            // error handling
            if (error != null) {
                Log.w("listen:error", error);
                return;
            }

            //update the list to reflect changes in the database
            ArrayList<Book> dbBooks = new ArrayList<>();
            for (DocumentSnapshot doc : value.getDocuments()) {
                dbBooks.add(new Book(doc.getId(), (String) doc.getData().get("Title"), null, null, null));
            }

            books.setValue(dbBooks);
        });
```
This works lol

2020-10-23 02:17 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                });
```suggestion
                .addOnSuccessListener(aVoid -> Log.d("Create", "Document succesfully written"))
                .addOnFailureListener(e -> Log.w("Create", "DocumentSnapshot not written", e));
```
same here

2020-10-23 02:17 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    .addOnSuccessListener(new OnSuccessListener<Void>() {
Added a suggestion in my review which can be commited through github

2020-10-23 02:45 UTC, armiantos approved these changes
Looks good to me!

## TODO
- Refactor book collection name in proper Firebase integration PR
- Remove dummy data

2020-10-23 02:46 UTC, cyrusdiego approved these changes
LGTM!

2020-10-23 02:47 UTC, merged

2020-10-23 02:53 UTC, calebschoepp reviewed
LGTM