Display a list of books in Unlibrary
CMPUT301F20T24/Unlibrary pull request #47
Opened 2020-10-23 09:11 UTC by armiantos

## Summary
- Depends on #42 
- Generalizes `BooksRecyclerViewAdapter`
- Give example on how to take advantage of Material Typography

## TODO
- Set-up `UnlibraryRepository`

2020-10-23 09:13 UTC, armiantos commented
Closes #47

2020-10-23 09:15 UTC, armiantos commented
This PR doesn't have to be pushed through if we decide to use a common `RecyclerViewAdapter` for all Exchange, Library, Unlibrary. This does not mean a waste of time in the Sprint as we learned a lot on `DataBinding` best practices and its limitations.

2020-10-23 17:01 UTC, cyrusdiego reviewed
Just left some nits regarding documentation. Regarding the adapter, I definitely think it can be abstracted to a common class across the 3 lists @armiantos @Taranjot-Singh @ghassanzadeh I think it would be a good idea to meet up or discuss in discord to discuss a possible design for this so we can just reuse the classes.

2020-10-23 17:32 UTC, armiantos commented
@cyrusdiego more than generalizing the adapter, we can just mark BookRecyclerViewAdapter as a concrete class (rather than an abstract) since it's the same list, we can just instantiate them in the 3 fragments individually and link it to different view models. We can definitely discuss today.

2020-10-23 18:03 UTC, cyrusdiego commented
> @cyrusdiego more than just generalizing the adapter, we can just mark BookRecyclerViewAdapter as a concrete class (rather than an abstract) since it's the same list, we can just instantiate them in the 3 fragments individually and link it to different view models. We can definitely discuss today.
> 
> But to sum it up, using this RecyclerViewAdapter means we'll have a single BookListFragment which will represent LibraryBooksFragment, UnlibraryBooksFragment and ExchangeBooksFragment (implicity merges the fragments together as well).

Okay yeah, that makes sense. Is this something we should allocate some time to actually sit down and discuss with @Taranjot-Singh and @ghassanzadeh (or just you three?) Since you three are working on the three lists.

2020-10-27 18:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
> +    public UnlibraryRepository() {
Added :)

2020-10-27 18:01 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
> +public class UnlibraryRepository {
Added :)

2020-10-27 21:10 UTC, cyrusdiego requested changes
Just left some nits, otherwise I think it should be good to go soon :)

2020-10-27 21:10 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +    public BookViewHolder<FragmentBookCardBinding> onCreateViewHolder(ViewGroup parent, int viewType) {
Nit: method headers for this method and below

2020-10-28 02:01 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +    public BookViewHolder<FragmentBookCardBinding> onCreateViewHolder(ViewGroup parent, int viewType) {
Added!

2020-10-28 02:08 UTC, cyrusdiego requested changes
Almost there :') left some nits and some notes to create issues for TODO's.

2020-10-28 02:08 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
>                  // TODO: change this to get image urls and user ids to customize the exchange list
Can you create an issue for this?

2020-10-28 02:08 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    public void setOwner(String owner) {
Nit: method header

2020-10-28 02:08 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Book.java
>      // TODO: Check if there's a better way of holding this information without making another fetch request to the database to retrieve Requests
Please create an issue for this as well

2020-10-28 02:23 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
>                  // TODO: change this to get image urls and user ids to customize the exchange list
For sure!

2020-10-28 02:25 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    public void setOwner(String owner) {
Added!

2020-10-28 08:08 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
>                  // TODO: change this to get image urls and user ids to customize the exchange list
#67  was opened but I figured we could delete the constructor here now that we're using custom objects in Firestore which will automatically handle this for us.

2020-10-28 08:12 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
>      // TODO: Check if there's a better way of holding this information without making another fetch request to the database to retrieve Requests
Opened #68

2020-10-31 07:29 UTC, calebschoepp requested changes
Fantastic work @armiantos . Bunch of comments but I think we're near to shipping this.

Sidenote. Depending on whose PR merges first (probably yours) we may need to work together a bit to figure out rebasing all the other changes.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksFragment.java
> +package com.example.unlibrary.book_list;
If this is a general book list why is it nested under Unlibrary?

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +
nit: Extra newline here

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +     * @return
Nit: These are empty. I'm okay with this if you meant to leave them empty.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +package com.example.unlibrary.book_list;
Again just confused why this is under unlibrary and not its own package like `booklist` or something.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksSource.java
> +    LiveData<ArrayList<Book>> getBooks();
Nit: This could be `List<Book>` instead of `ArrayList<Book>` b/c the interface doesn't care about the implementation of the list.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +    }
IMO this should just be done in `onCreateView`. I see no reason in doing it here instead.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +        mBinding.setLifecycleOwner(getViewLifecycleOwner());
Is this even necessary if you aren't binding any data in the xml via something like `mBinding.setViewModel(mViewModel)`?

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +        mBinding.setLifecycleOwner(getViewLifecycleOwner());
Actually just saw you're doing `setBookSource` below.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +        }
Can you help me understand why you're doing it this way? Why aren't you just including the book list fragment and passing the viewModel via data-binding in the xml? I always feel like `instanceof` is a code smell.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +    private static final String TAG = "EXCHANGE_REPOSITORY";
Another pattern I've seen in Java codebases at work is `private static final String TAG = ExchangeRepository.class.getSimpleName()`. Either way is probably fine.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
>      private static final String BOOKS_COLLECTION = "Books";
I'd like to strongly advocate that we move to the collection name `books` as per my RFC (`requests`, `users` etc.) . In all my work with data modelling table/field names have been `snake_case` without a starting capital.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +                    for (DocumentSnapshot doc : value.getDocuments()) {
Maybe leave a TODO here to use `getDocumentChanges` so that we are only pulling down the diff. Will require more logic but would be more efficient. Outside the scope of this PR though.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
> +     * @return
Nit: Left empty. Same comment as above.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
> +        }
Same questions as above.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
> +    }
There will be conflicts here with my PR but that is fine. We can handle in rebase.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +    private static final String BOOK_COLLECTION = "Books";
Same comment.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    Log.d("Create", "Document succesfully written");
Shouldn't this use `TAG`?

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    Log.w("Create", "DocumentSnapshot not written", e);
Shouldn't this use `TAG`?

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        Log.d("Delete", "Data has been deleted successfully!")
Multiple missing TAG.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    @DocumentId
My PR will be including `@Exclude` annotation here so that we don't store id in firestore. That would be redundant.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    public void setPhotos(ArrayList<String> photos) {
He responded on my forum post and said that primary goal is one photo and secondary goal is multiple photos. Do we still want to support multiple off the bat?

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryFragment.java
> +        for (Fragment f : getChildFragmentManager().getFragments()) {
Lots of the same comments in this class as the previous classes.

2020-10-31 07:29 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
> +    }
Why is this in Unlibrary?

2020-10-31 07:54 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
> +    }
Right, removing!

2020-10-31 07:55 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    public void setPhotos(ArrayList<String> photos) {
Let's aim for single photo first.

2020-10-31 07:57 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    @DocumentId
Ah sorry I left a comment in your PR earlier. At the moment, in Firestore I don't see an explicit ID field. 
![Screenshot_20201031_015648](https://user-images.githubusercontent.com/43416725/97774327-5d1abe00-1b1c-11eb-8aa1-c52f3382f3a4.png)
Is adding @Exclude redundant since this ID will be present in Firestore anyway? I think @Exclude is meant for non ID fields to be excluded from the database, I could very much likely be wrong.

2020-10-31 07:58 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/book_list/BooksSource.java
> +    LiveData<ArrayList<Book>> getBooks();
Will refactor!

2020-10-31 08:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +    }
Shouldn't the ViewModel persist across different context changes? Moving this to onCreateView would mean we're retrieving the viewmodel class everytime the fragment is displayed from the back stack no? [Fragment Lifecycle](https://developer.android.com/guide/components/fragments)

2020-10-31 08:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +package com.example.unlibrary.book_list;
Unlibrary here is our package I believe.

2020-10-31 08:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +
Ah will remove!

2020-10-31 08:00 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/book_list/BooksFragment.java
> +package com.example.unlibrary.book_list;
I believe unlibrary is our app package.

2020-10-31 21:50 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksFragment.java
> +package com.example.unlibrary.book_list;
LMAO. Of course, I'm so dumb hahaha. This is hilarious.

2020-10-31 21:51 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +package com.example.unlibrary.book_list;
Actually I guess now that I think about it, does it belong in the `util` package maybe? Instead of the root of project?

2020-10-31 21:51 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    @DocumentId
We talked on Discord about this. It seems your testing shows that @exclude is redundant.

2020-11-01 20:19 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +package com.example.unlibrary.book_list;
This is in a module called book_list, do we still want to move it to util? I placed it here because it's associated with a fragment.

2020-11-01 20:22 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +     * @return
We can infer from the parent class. Adding!

2020-11-01 20:24 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +        mBinding.setLifecycleOwner(getViewLifecycleOwner());
Yea I opened an issue to see if we can pass the ViewModel from parent fragment to child fragments from xml. @drojasca  will look into that this week.

2020-11-01 20:27 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
> +        }
It is, I don't like this style either but I spent sometime reading and trying things like using [BindingAdapters](https://developer.android.com/topic/libraries/data-binding/binding-adapters) so we can pass the viewmodel via xml but i couldn't get it working. So I opened #72

2020-11-01 20:29 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +    private static final String TAG = "EXCHANGE_REPOSITORY";
yes pls thank you :'D

2020-11-01 20:30 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +                    for (DocumentSnapshot doc : value.getDocuments()) {
Will do!

2020-11-01 20:35 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
> +     * @return
Added!

2020-11-01 20:35 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
>      private static final String BOOKS_COLLECTION = "Books";
Will do!

2020-11-01 20:36 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
> +        }
Refer to [original thread](https://github.com/CMPUT301F20T24/Unlibrary/pull/47#discussion_r515667888)

2020-11-01 20:36 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
> +    }
Yes yes

2020-11-01 20:36 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +    private static final String BOOK_COLLECTION = "Books";
Refer to [original thread](https://github.com/CMPUT301F20T24/Unlibrary/pull/47#discussion_r515668800)

2020-11-01 20:37 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    Log.d("Create", "Document succesfully written");
Yes will add!

2020-11-01 20:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                    Log.w("Create", "DocumentSnapshot not written", e);
Yes I missed these, thanks for catching them!

2020-11-01 20:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
> +                        Log.d("Delete", "Data has been deleted successfully!")
Added

2020-11-01 20:40 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    @DocumentId
Will merge with #75 appropriately

2020-11-01 20:44 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryFragment.java
> +        for (Fragment f : getChildFragmentManager().getFragments()) {
Refer to [original thread](https://github.com/CMPUT301F20T24/Unlibrary/pull/47#discussion_r515667888)

2020-11-01 21:49 UTC, calebschoepp approved these changes
LGTM! Great work @armiantos

2020-11-01 21:49 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/book_list/BooksRecyclerViewAdapter.java
> +package com.example.unlibrary.book_list;
Lol. Just forget everything I've said. In my head I was interpreting `book_list` as the class name. This is great.

2020-11-01 23:03 UTC, armiantos commented
Thanks! I'll create a reformat whole project PR as well.

2020-11-01 23:05 UTC, merged

2020-11-01 23:16 UTC, ghassanzadeh approved these changes
LGTM! Great work @armiantos!

2020-11-01 23:16 UTC, ghassanzadeh commented on app/src/main/java/com/example/unlibrary/models/Book.java
> -    public String stringStatus() {
Nice, this is a way better way to get the book status!