Profile Page
CMPUT301F20T24/Unlibrary pull request #59
Opened 2020-10-25 21:59 UTC by cyrusdiego

# Summary
- Created UI for the profile page 
    - Created two reusable UI parts (`fragment_editable_text` and `fragment_image_holder`) 
    - Shows user's email and username (both are editable)
    - Editing email will update firebase auth and firestore
- Instantiate Profile ViewModel in MainActivity level 

## ToDo
- Unit testing for ViewModel 
- UI testing for Profile Fragment 
- Validating email and username prior to confirming (i.e. ensure it's a valid email and that the username is unique)
- Edit profile picture 
- Password protect updating email (?)

Closing #35

2020-10-26 03:16 UTC, calebschoepp requested changes
Wowowow great work Cyrus! That was some super clean, idiomatic, and downright beautiful code I just read. Bunch of comments so not quite ready for the sign off yet but it is getting there!

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +        mBinding.logoutButton.setOnClickListener(view -> logout());
Can this be done as a Lambda inline on the xml (via data-binding) or are you doing this because the XML is modular?

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +     * TODO Implement Logout
Can you file a ticket for this if there isn't one already?

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +            mViewModel.updateProfile();
Should you be checking for an exception here and not exiting the edit mode? It seems to me that updateProfile can fail. For example, updating to an invalid email or not globally unique username should fail.

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +    private final String USERNAME_FIELD = "username";
Can't these all be `static` too? They aren't changing on a per-instance basis.

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +        mFirebaseUser = FirebaseAuth.getInstance().getCurrentUser();
Should you check for null here? Not quite sure how that could ever happen b/c everything should be protected/authenticated via the Auth Activity "middleware" I setup, but ya know, better safe than sorry? Not sure how much of a pain this check would be.

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +                        for (QueryDocumentSnapshot document : task.getResult()) {
Wait I'm confused. When could this ever possibly return multiple users?

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +    }
Have you checked that the `updateEmail` method works as we expect it to? That is, have you changed your email and still been able to log in with the new email and same password?

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +    }
This needs to first verify that the username is globally unique. Look in `AuthRepository` for an idea of how to approach this.

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +     * TODO Be able to edit profile picture
Please file a ticket for this if there isn't already one.

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +    }
Are you intending to just show toasts or something like that on failure/success? You can probably use the `SingleLiveEvent` pattern.

Also, should this maybe signal failure if something goes wrong so the user doesn't get kicked out of editing?

2020-10-26 03:16 UTC, calebschoepp commented on app/src/main/res/layout/fragment_editable_text.xml
> +                android:text="@={content}" />
You may want to set the `maxlines = 1` attribute.

2020-10-26 04:23 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +        mBinding.logoutButton.setOnClickListener(view -> logout());
I set the binding like this because for UI specific functionalities I have the implementation in the `ProfileFragment` source file. For data-related logic, it's in the ViewModel or if it's edit state-related I have it in the edit state object. Because of this, we can't set this on click listener directly in the XML unless we create a class that encapsulates the UI specific functionality.

2020-10-26 04:27 UTC, drojasca requested changes

2020-10-26 04:27 UTC, drojasca commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +        mUID = mFirebaseUser.getUid();
I am having issues running the code. It's giving me a null pointer exception, most likely because I am not logged in.

2020-10-26 04:28 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +        mUID = mFirebaseUser.getUid();
Will look into this, I think I know the problem, I thought I resolved it but I may need to do a fresh install anytime I'm testing this

2020-10-26 05:14 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +        mBinding.logoutButton.setOnClickListener(view -> logout());
Makes sense. Fine by me.

2020-10-26 06:44 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/MainActivity.java
> +        mProfileVM = new ProfileViewModel();
Is there a reason for us instantiating this in the MainActivity?

2020-10-26 06:46 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +     * TODO Implement Logout
Ticket created #63

2020-10-26 06:54 UTC, armiantos reviewed
Left some comments and need to discuss whether to initialize class properties in the declaration or initialize them on get(). Overall great job!

2020-10-26 06:54 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +                        for (QueryDocumentSnapshot document : task.getResult()) {
I think the getResult will return an iterator containing just one user but with `task.isSuccessfull() && task.getResult != null)` I think it's safe to do task.getResult()[0]. Also is there a reason why you're using onCompleteListener instead of onSuccess listener? (with this you can skip the task.issuccessful check)

2020-10-26 06:54 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +        if (mUserName == null) {
We might need to discuss which pattern is best to stay consistent, since this will always evaluate to false given that we initialize mUserName in line 18.

2020-10-29 03:09 UTC, armiantos reviewed
Awesome improvements! We still need to talk about whether to instantiate member variables in the constructor or to use lazy initialization on get with the team.

TODO
- Create another PR to refactor User to use `@DocumentId` so that it can be used without explicitly converting fields in the repositories

2020-10-29 03:09 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +                });
Should we try to mimic what was done in `AuthViewModel` where we have a sequence of try catches instead of a nested structure?

2020-10-29 03:09 UTC, armiantos commented on app/src/main/res/layout/fragment_profile.xml
> +            app:title="@{`Username`}" />
Just curious what the \`'s are

2020-10-30 02:20 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +        mViewModel.fetchUser();
Moving to the constructor, that was a relic from when I was initially doing this and had to delay fetching the user until the user was logged in, but it should be fine now

2020-10-30 02:20 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +            if (isEditing == null) {
Will create an Issue highlighting this design choice

2020-10-30 02:27 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +                });
I actually opted to not use the `User` model in this case, I don't have hard opinions on this but I chose to do it like this as in the UI, we are only concerned with acquiring the username, email, and eventually the profile picture of the current user from the DB. Because of this, I didn't see the need to store the information in a `User` entity object. Also, in my `ProfileViewModel` I'm not actually storing a `User` entity object, but just email, username, and eventually an image. If this doesn't seem very good I can change it make a TODO for this. what are your thoughts? (Or did I completely misunderstand your comment??)

2020-10-30 02:29 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_profile.xml
> +            app:title="@{`Username`}" />
Oh so, if you want to pass a string you need to wrap in `

2020-10-30 02:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +                });
I was having some trouble with this part and was facing some callback hell. I am first re-authenticating the user, if successful then I attempt to update the email (in Firebase Auth and Firestore), if that's successful then I update the username. The reason I do this nested structure is so that they all get updated at once. I think I am going to update the PR a bit so that each can be updated separately and there will be an associated UI indication.

I thought about doing a sequence of try catches but since I wanted the updates to happen all at once I opted for nesting. Will look into this more as I'm definitely not a fan of this implementation.

2020-10-31 07:17 UTC, armiantos commented on app/src/main/res/layout/fragment_profile.xml
> +            app:title="@{`Username`}" />
Can't it just be `"Username"` then?

2020-10-31 07:21 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +                });
Ah I see, that's fair. Was just wondering if this would be cleaner 
```
addOnSuccessListener(task -> {
    User user = task.getDocuments().get(0).toObject(User.class);
    onFinished(true, user.getName(), user.getEmail());
});
```
So we're not hardcoding the field strings.

2020-10-31 07:22 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +            if (isEditing == null) {
Agreed to use lazy initialization. We can make the lazy inits a separate PR to clean everything else as well.

2020-10-31 07:22 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_profile.xml
> +            app:title="@{`Username`}" />
Can't be `"Username"` but I realize I can do `"@{@string/username}"` reason I have to wrap it is that I'm passing down data to a variable held by the reusable fragment. I'm pretty sure I couldn't get `"Username"` working but I'll double-check

2020-10-31 07:22 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileFragment.java
> +        mViewModel.fetchUser();
Sweet!

2020-10-31 07:24 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +        if (mUserName == null) {
Agreed to use lazy initialization.

2020-10-31 07:24 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +                });
Yes, that makes sense, actually. I realize by doing it like this I can make the code highlighted below (i.e. the callback stuff) a lot cleaner since I'm updating each field separately.

2020-10-31 07:25 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +                });
Will be changing this in an upcoming commit, just FYI. Figured a better way to deal with this

2020-11-02 00:36 UTC, calebschoepp reviewed
Super close @cyrusdiego , just a couple of nits. Ping me once you've fixed them or chosen to not fix them and I'll give you the LGTM and approve the PR.

2020-11-02 00:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
Nit: Maybe run formatting in this file. Looks like there are some extra lines.

2020-11-02 00:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +
Nit: Extra newlines. Run formatter here maybe.

2020-11-02 00:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +
Nit: Extra newlines

2020-11-02 00:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +
Going to stop commenting on them as I see them b/c it appears it is just a stylistic difference between how you and I write code, 1 line vs 2 line gaps.

I'm not too concerned with it either way but if the formatter would bring the gaps down to 1 line then my preference is we would follow that. If it does not, I'm happy to just leave it.

2020-11-02 00:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +    private ProfileRepository mProfileRepository = new ProfileRepository();
Nit: Should this be happening in the constructor? Not sure if there is really any semantic difference when doing it here.

2020-11-02 00:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +    }
Nit: This can probably be extracted to `AuthUtil` like the validation stuff was too. The exact same enum is found in `AuthViewModel`.

2020-11-02 00:36 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/util/AuthUtil.java
> +package com.example.unlibrary.util;
File header comment.

2020-11-02 02:15 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +    private ProfileRepository mProfileRepository = new ProfileRepository();
I don't think there's any difference in initializing in the constructor vs in the declaration. Are you referring to the `ProfileRepository` or all of the class attributes?

2020-11-02 02:16 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
> +
Weird, I ran the formatter and it didn't seem to remove the extra newlines.

2020-11-02 05:09 UTC, calebschoepp approved these changes
LGTM!

2020-11-02 05:09 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/profile/ProfileViewModel.java
> +    private ProfileRepository mProfileRepository = new ProfileRepository();
Just the profile repository. Not too worried about it. Resolving comment.

2020-11-02 05:14 UTC, drojasca approved these changes
LGTM

2020-11-02 05:15 UTC, merged