Taran golnoush/exchange fragment improved
CMPUT301F20T24/Unlibrary pull request #62
Opened 2020-10-26 03:25 UTC by ghassanzadeh

- Created the exchange fragment to show the list of requested and available books
    - TODO: need to find out how to get the id of the logged in user and the book owner to customize the view for each fragment
   - TODO: need to know how to store the images taken by the camera to retrieve in the view
- Made the first version of library layout to show all books and two floating buttons for filtering and adding books

2020-10-26 03:44 UTC, calebschoepp requested changes
Really, really great work guys. Exciting to see this coming together. Couple of things I'd like addressed before this merges.

Side note/super nit: I understand that the PR got to this point naturally (feature creep) but it would be great if we could keep the scope of PR's as narrow as possible in the future i.e. one PR for the exchange and one for the library.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +    public ExchangeBooksFragment() {
TBH don't think you need this as long as you don't define a constructor with arguments. That being said I'm fine to keep it around.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +        mViewModel = new ViewModelProvider(requireActivity()).get(ExchangeViewModel.class);
I feel like we should probably setup a `mBinding` variable here. Look at Cyrus's PR for an example of how to do that.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +        mViewModel = new ViewModelProvider(requireActivity()).get(ExchangeViewModel.class);
Oh whoops, didn't see `onCreateView` below. IMO this can just move to `onCreateView` and we can get rid of `onCreate`.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +        if (view instanceof RecyclerView) {
This seems off to me but I don't know enough about recycler views to weigh in. @cyrusdiego @armiantos

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +    private ExchangeViewModel mViewModel;
Should this view model be instantiated in the `ExchangeBooks` fragment and the information passed down to `ExchangeBooksFragment`?

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +    MutableLiveData<ArrayList<Book>> books;
We've been trying to us an `m` prefix for all member variables.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +        query = db.collection("Books");
Please make "Books" a member variable like `private static final String BOOKS_COLLECTION = "books"`

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +                Log.w("listen:error", error);
Isn't first arg to Log a tag?

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +                if (doc.getData().get("mStatus").equals("AVAILABLE") || doc.getData().get("mStatus").equals("REQUESTED")) {
Same with all these field names. Please make them member variables.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +    public String stringStatus(){ return mStatus.toString();
Weird formatting here.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/res/layout/fragment_exchange.xml
> +            android:layout_marginRight="16dp"
Any reason for all these specific and variable margins?

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/res/layout/fragment_exchange.xml
> +            android:hint="Search for books to borrow..."
Extract to `strings.xml`

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/res/layout/fragment_exchange.xml
> +            app:layout_constraintVertical_bias="0.943" />
This feels like a really big code smell to me. What is the point of this?

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/res/layout/fragment_exchange.xml
> +
Please remove all these extra lines.

2020-10-26 03:44 UTC, calebschoepp commented on app/src/main/res/layout/fragment_library.xml
> +            android:layout_marginLeft="10dp"
We should really extract this to a style if we're going to use this everywhere.

2020-10-26 03:51 UTC, calebschoepp commented
> TODO: need to know how to store the images taken by the camera to retrieve in the view

I'll be covering this in my work with the camera this week.

> TODO: need to find out how to get the id of the logged in user and the book owner to customize the view for each fragment

You can look at Cyrus's PR to get an idea of how to do this.

2020-10-26 03:53 UTC, calebschoepp commented
Please lowercase the `books` collection.

2020-10-26 19:02 UTC, armiantos reviewed
Left some minor comments. Great job and awesome improvement over the last PR. 

One important discussion that we need to have is which do we want to merge first (this or #47). Looking at the size of the PR, I'd rather have this merged first so that #47 can do a simple refactor on exchange and library along with refactoring the repository changes.

2020-10-26 19:38 UTC, cyrusdiego reviewed
Good job guys! I left some comments as well, I think for the most part there are some discussions we should have regarding the styling as well as the recycler view re-usability across the 3 pages. Thanks guys :)

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBookRecyclerViewAdapter.java
> +    public ExchangeBookRecyclerViewAdapter(ArrayList<Book> items) {
Nit: method header

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBookRecyclerViewAdapter.java
> +    public void setData(ArrayList<Book> items) {
Nit: method header

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +    private ExchangeViewModel mViewModel;
I think the view model should be instantiated on the activity level as well, then accessed in the fragment level.

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +        if (view instanceof RecyclerView) {
I'm wondering if there's a better way to inflate and set up the recycler view, correct me if I'm wrong but I find the use of `instanceof` not being very good practice (just something to think about but would need to look into this more online on how other people set up the recycler view)

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
> +        query = db.collection("Books");
I suppose since all the pages would be querying the same collections (books, users, etc.) would it be worthwhile moving these constants to yeah `string.xml`? Thing is, I've only seen the use of `string.xml` to be for UI related strings, not constant strings used in source files.

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +     * TODO: link logged in user with the owner of books to modify the book lists in each fragment
Please make an issue for this so we can track pending TODOs

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +
nit: extra line

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_exchange.xml
> +            android:layout_marginRight="16dp"
I think we can probably leave these for now, though we will need to revisit our UI mockup and re-hash the little details like margins, text size and types, etc. so we have a formal redline design doc @armiantos thoughts on this? This would probably entail a separate PR that will handle all styling for the app or individual PR's that will updating the styling per page

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_exchange.xml
> +            app:layout_constraintVertical_bias="0.943" />
I think you can replace this with `<include>` then we can have the margins and such be defined within the fragment itself so that it's common for all book lists.

2020-10-26 19:38 UTC, cyrusdiego commented on app/src/main/res/layout/fragment_exchange.xml
> +            app:layout_constraintVertical_bias="0.943" />
oh wait I realize that we haven't created a generic recycler view to create generic/reusable UI component. @armiantos that's your draft PR right?

2020-10-27 04:58 UTC, ghassanzadeh commented on app/src/main/res/layout/fragment_exchange.xml
> +            app:layout_constraintVertical_bias="0.943" />
This is just for placing the exchange fragment under the search bar.

2020-10-27 05:35 UTC, ghassanzadeh commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +    private ExchangeViewModel mViewModel;
Do we still have activity for each list?

2020-10-27 06:42 UTC, armiantos commented on app/src/main/res/layout/fragment_exchange.xml
> +            app:layout_constraintVertical_bias="0.943" />
Yep, that's my PR, don't worry too much about layout implementation. I think the focus of this PR should be the repository filtering.

2020-10-27 07:05 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
> +        if (view instanceof RecyclerView) {
There is and I was able to do it using binding. Looks something like this
```java
        mBinding = FragmentBookListBinding.inflate(inflater, container, false);
        RecyclerView view = mBinding.getRoot();
```
but yes this will be taken care of in my refactor.

2020-10-27 19:12 UTC, calebschoepp approved these changes
LGTM!

2020-10-27 19:13 UTC, merged