Add some basic CI
CMPUT301F20T24/Unlibrary pull request #7
Opened 2020-10-02 18:46 UTC by calebschoepp

## Changes
- Run unit tests in CI
- Run linting in CI

## Notes
- Need to un-comment rest of CI once we start using Firebase

2020-10-02 19:05 UTC, cyrusdiego requested changes

2020-10-02 19:05 UTC, cyrusdiego commented on .github/test.yml
> +      # Step 4: Assemble debug apk to send to firebase test lab
So I just wanted to confirm these steps: it seems these steps are for instrumentation test? And then we would assembly our apk and send to firebase test labs. Is my understanding correct?

2020-10-02 19:06 UTC, calebschoepp commented on .github/test.yml
> +      # Step 4: Assemble debug apk to send to firebase test lab
Yep that's right. See here for more details. https://www.coletiv.com/blog/android-github-actions-setup/

2020-10-02 19:06 UTC, calebschoepp commented on .github/test.yml
> +      # Step 4: Yun your unit tests
Nice

2020-10-02 19:12 UTC, calebschoepp commented
FYI: I know tests are failing, just need to work on something else this afternoon. Will fix this later tonight hopefully

2020-10-02 19:13 UTC, cyrusdiego requested changes
The build seems to be failing still, I think we need to have an assembleStagingDebug file in our project directory?

2020-10-03 02:47 UTC, calebschoepp commented
@cyrusdiego the tests are passing now. Just waiting for a LGTM!

2020-10-04 04:47 UTC, cyrusdiego approved these changes
LGTM :D

2020-10-04 05:14 UTC, merged