WIP: Styling
CMPUT301F20T24/Unlibrary pull request #91
Opened 2020-11-04 04:00 UTC by calebschoepp

# Summary
- List of features this PR will add

# Screenshots
- If you're working on UI

# TODO
- List of tasks that is too big for this PR and will be done in future PRs or some known issues to fix
- Don't forget to create new tasks to monitor these

Closes insert-issue-number-here

2020-11-04 19:30 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
> +        mUpdateFilter.setMap(mViewModel.getFilter().getMap());
This is a bug fix.

2020-11-04 19:37 UTC, cyrusdiego requested changes
Just left a nit but other than that I think it looks good! Ping me when you add the change and I can approve

2020-11-04 19:37 UTC, cyrusdiego commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        public String asLower() {
nit: method header

2020-11-04 19:41 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        public String asLower() {
Might want to see if we can use [android:capitalize](https://developer.android.com/reference/android/widget/TextView#attr_android:capitalize)

2020-11-04 21:41 UTC, armiantos commented
Nice branch name

2020-11-04 21:55 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        public String asLower() {
`android:capitalize` won't work. I'm thinking capitalize should be a util and the xml should invoke that util instead so that `Book` isn't concerned in giving the lower cased enum.
```xml
                    android:text="@{StringUtil.capitalize(book.status.toString())}"
```
```java
public class StringUtil {
    public static String capitalize(String str) {
        if(str == null || str.isEmpty()) {
            return str;
        }

        return str.substring(0, 1).toUpperCase() + str.substring(1).toLowerCase();
    }
}
```

2020-11-04 21:56 UTC, armiantos commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        public String asLower() {
Then again I don't think this'll be used anywhere else so I think it's fine (lol sorry for the going back and forths)

2020-11-04 23:04 UTC, armiantos reviewed
LGTM! Just some nit comments

2020-11-04 23:04 UTC, armiantos commented on app/src/main/res/layout/fragment_exchange_book_details.xml
> +            android:id="@+id/textView9"
Should we start naming these?

2020-11-04 23:04 UTC, armiantos commented on app/src/main/res/layout/fragment_library_edit_book.xml
> +            android:layout_marginEnd="16dp"
Isn't this redundant since we have `layout_margin` just before?

2020-11-05 01:18 UTC, calebschoepp commented on app/src/main/java/com/example/unlibrary/models/Book.java
> +        public String asLower() {
Lol no problem. If we start writing capitalization code elsewhere we can extract it to a util then.

2020-11-05 01:19 UTC, calebschoepp commented
> Nice branch name

Glad someone noticed :laughing:

2020-11-05 01:20 UTC, calebschoepp commented on app/src/main/res/layout/fragment_exchange_book_details.xml
> +            android:id="@+id/textView9"
Maybe? I cared about this at the start of the project but have since stopped caring because I got tired of coming up with id names for every single tag. Happy to climb back on the horse if it is deemed worthwhile.

2020-11-05 01:21 UTC, calebschoepp commented on app/src/main/res/layout/fragment_library_edit_book.xml
> +            android:layout_marginEnd="16dp"
Yep it is. Good catch. I have removed it.

2020-11-05 02:04 UTC, armiantos commented on app/src/main/res/layout/fragment_exchange_book_details.xml
> +            android:id="@+id/textView9"
Actually nah its all good, if we rename we have to make sure its unique lol. I just realized we're not referring to these in code.

2020-11-05 02:05 UTC, armiantos approved these changes
Looks a pretty a good to me :100:

2020-11-05 03:41 UTC, cyrusdiego approved these changes

2020-11-05 03:47 UTC, cyrusdiego approved these changes
approved! x2 :D

2020-11-05 03:58 UTC, merged