WIP: Update UML Diagrams
CMPUT301F20T24/Unlibrary pull request #95
Opened 2020-11-04 20:21 UTC by cyrusdiego

# Summary
- Updating UML diagram for part 3 submission
- I split it into two parts (as of Nov 4 1:17pm) as it was very messy keeping it in one file 
- Will need help from @armiantos @ghassanzadeh @Taranjot-Singh regarding the `BookList` objects 

# Screenshots
![Auth](https://user-images.githubusercontent.com/32345990/98163653-54b9de80-1ea0-11eb-9db3-4ad428748a88.png)
![MVVM](https://user-images.githubusercontent.com/32345990/98163656-5683a200-1ea0-11eb-9fd7-408726295885.png)

Closes #52

2020-11-04 20:52 UTC, ghassanzadeh reviewed
Thanks @cyrusdiego! We added extra classes like ExchangeBookDetailsFragment, LibraryEditBookFragment, etc. Will modify the Exchange Fragment and can help with the rest as well. :)

2020-11-04 21:31 UTC, armiantos reviewed
Great job listing the responsibilities! Just a few nits we could make it even better :rocket:

2020-11-04 21:31 UTC, armiantos commented on doc/MVVM-UML.txt
> +'------------------- BookFragment  -------------------------------
```suggestion
'------------------- BooksFragment  -------------------------------
```

2020-11-04 21:31 UTC, armiantos commented on doc/MVVM-UML.txt
> +class BookFragment {
```suggestion
class BooksFragment {
```

2020-11-04 21:31 UTC, armiantos commented on doc/MVVM-UML.txt
> +UnlibraryViewModel ..o BookFragment
This is done in implementation but I think it'd be better to hide this and instead mark `<<uses>>`from `BooksFragment` to `BooksSource`. Since this is the sole purpose of `BooksSource`

2020-11-04 21:31 UTC, armiantos commented on doc/Auth-UML.txt
> +MainActivity --|> AuthenticatedActivity: <<extends>>
```suggestion
AuthenticatedActivity <|-- MainActivity: <<extends>>
```
So AuthenticatedActivity appears on top

2020-11-04 21:31 UTC, armiantos commented on doc/MVVM-UML.txt
> +UnlibraryViewModel ..o BookFragment
`BooksFragment` doesn't actually know anything about the viewmodels, it just calls `getBooks`

2020-11-04 21:33 UTC, armiantos commented on doc/Auth-UML.txt
> +MainActivity --|> AuthenticatedActivity: <<extends>>
![](http://www.plantuml.com/plantuml/png/bLHDR-8m4BtxLrZYiB1iilTL586subGkYFRkEgDWDTWeCu4Ysl_UZ24VRYXjSx7y_DuRzDw86P8ggTeMubSq_EHI6IldcipUqF6Fd5UqwLsLpJm4benM1DdvZOuoklq9NIX4hstSv4cCzivaqjd_9IY2yKHCFO0RTrYKAj-2fG1SEuMCl8cBtxtBZMsejU7qqS2XDUHBdxs2t211-Mq1Xt7ZvxR4C9DRYiW3kLixbjJ0Q65AU5883mYbp87uF5jVDutZD8ZndqoIGbLMRm3Jz1DHydgfjg-25mARDQAM-pkEmrm7puCWnVLTuZYNBeF2xyqATWuDkT80oh6V8F-sLXFvWnNgZ4yYyawj-L4MuLrCFQ6LZB_WVsYrU-1PJLbyOWs2l3BExE5EaKguoRIfb95sbxLVXwxfdTBFAWVPsPvgD1pFnNS4xazf3OY0gGWpOMAePNQ5CAYQcO6sHvo1pVXVuXq0)

2020-11-04 21:37 UTC, armiantos reviewed
Ok my comments were duplicated, then I tried to delete the duplicates but that deleted both of them :')

2020-11-04 21:37 UTC, armiantos commented on doc/MVVM-UML.txt
> +UnlibraryViewModel ..o BookFragment
`BooksFragment` doesn't actually know these viewmodels, I think it'd be better to link it with `BooksSource` via `<<uses>>`

2020-11-04 21:37 UTC, armiantos commented on doc/MVVM-UML.txt
> +interface BookSource {
```suggestion
interface BooksSource {
```

2020-11-04 21:37 UTC, armiantos commented on doc/MVVM-UML.txt
> +interface BookSource {
Or do we want to rename it in source code lol. I called it Books because it represents books (plural) but totally down to renaming it to just Book.

2020-11-04 22:27 UTC, cyrusdiego commented on doc/MVVM-UML.txt
> +interface BookSource {
All good, I'm good with `BooksSource`

2020-11-04 22:33 UTC, cyrusdiego commented on doc/MVVM-UML.txt
> +UnlibraryViewModel ..o BookFragment
Would something like 

```plaintext
ExchangeViewModel ..|> BooksSource: <<implements>>
BooksSource ..o BookFragment
...
```
![image](https://user-images.githubusercontent.com/32345990/98174952-eb8f9680-1eb2-11eb-9fb5-a2347474364d.png)

be better? I could be misunderstanding the design but I thought that we pass the `BooksSource` to the `BookFragment` so I thought it could be aggregation. (i.e. `BooksSource` is a part of `BookFragment`) I'm ok with:

```plaintext
ExchangeViewModel ..|> BooksSource <<implements>>
ExchangeViewModel <.. BookFragment: <<uses>> 
...
```
![image](https://user-images.githubusercontent.com/32345990/98175020-0d891900-1eb3-11eb-9f9e-658d57babe60.png)

... as well. What're your thoughts?

2020-11-04 23:01 UTC, armiantos commented on doc/MVVM-UML.txt
> +UnlibraryViewModel ..o BookFragment
Ah yes the first one seems more accurate. `ViewModel` implementing `BooksSource` and that `BooksSource` is used in `BooksFragment`. A+ for attention to detail.

2020-11-05 01:10 UTC, armiantos reviewed
Most of the things look solid! Really nice and readable. One question, should we put the fragments up top with backend (Firestore and repositories) at the bottom like in Auth-UML or otherway around?

2020-11-05 01:10 UTC, armiantos commented on doc/UML/Auth-UML.txt
> +AuthActivity ..> AuthViewModel: <<uses>>
```suggestion
LoginFragment ..> AuthViewModel: <<uses>>
RegisterFragment  ..> AuthViewModel: <<uses>>
```
To be consistent with MVVM-UML.txt, would it be better to link the viewmodels to the fragments?
In implementation, I don't think AuthActivity uses the ViewModel other than implicitly instantiating the viewmodel for the fragments. As always open to discussion.

2020-11-05 01:10 UTC, armiantos commented on doc/UML/MVVM-DetailedFragments-UML.txt
> +@startuml
This looks good!
![image](https://user-images.githubusercontent.com/43416725/98184742-5bf4e280-1ec8-11eb-8f6f-d43c40e59ba2.png)
Abstracts away `Book` by passing it down to classes rather than linking every single object with the `Book` class

2020-11-05 01:12 UTC, cyrusdiego commented on doc/UML/Auth-UML.txt
> +AuthActivity ..> AuthViewModel: <<uses>>
oh yes that makes sense actually. will commit this change

2020-11-05 03:12 UTC, ghassanzadeh commented
We have three more classes that are missing in this diagram: AuthUtil, BarcodeScanner, CustomImageBinding

2020-11-05 05:02 UTC, armiantos reviewed
Awesome job team! Left some suggestions and their previews. I didn't look at each of the methods yet, but will do soon.

2020-11-05 05:02 UTC, armiantos commented on doc/UML/Auth-UML.txt
> +AuthViewModel <.. RegisterFragment: <<uses>>
```suggestion
AuthViewModel <.. RegisterFragment: <<uses>>
AuthUtil <.. AuthViewModel: <<uses>>
```

2020-11-05 05:02 UTC, armiantos commented on doc/UML/Auth-UML.txt
> +AuthViewModel <.. RegisterFragment: <<uses>>
![](http://www.plantuml.com/plantuml/png/bLNVJzim47xFNs69Xy6WtVkeAWgqKhKM451UaKbEwMd-KTbE6MBxtvTpapWc3TtwqEJEdp_Rzts-N5Z7ZIkaIBuCkZ-svAZO97MuHVTsnYQ5MxT2hZAV0kKmvGwotPXxOuFFVqagkBL-Rit6tfDJYfyGNfSw0y5aytgU76qrPaohAmFSmV59SkeJTgrVPuRd4fIBae-QMyhyIQgb5Zf7LKDfBI9l22bee-yXH-l0_FC4gbFh98FwdVANg39KEPFLI-zXmAqsbzevBM_u5dFkKAizftfmnjFPl1nR6MGl1OfiXWBAeBsfI9hsxcPeu8LRM5amJD9_Tqz74IW7HyyTUtJOmU3tUFzAtzbe1BySgCoEnqcazMWux9yZUA7IDT2aMBNXy6jacIJ8r8VOx-hWCNBmFMoqHQSDWcN7VadshR702ViFCpV4L6NFr92_CH77oM1PEFuYO85RkEQEZtR2ZfcSIexYa_4xRkshDba_n8kgk8Hay50cTeZf5fGBa1b7KHXOsjmFT95t7Cs8ZhLoA8PpjIdS3oYlVSLGKipLbWlC_50FIQrDYQvVWxjxvZnfp4fyv90AIhbMJMKSdoSVcWXTdxuQvU2eq8SmTR4FmEg24wot1WJigSAUUMtw85OF-h1SH1CB5XF5vITqHu3GP5FV9oPfgekGtLayOBXAGJIXgMvKrA8Y-UZMLDrjzJ2zVxwwNIocLu_psvieVpDPJfzdy-dYEhGoUjgI0vYylWnfuj-PX9mHBHOwA-Pghkgs2cI9kcXiKub_ncxL31NQDMGBEeK2mtIJwXpn05cLA2hF76IFwaNobjyZK8LajSh9QKNfvUKElBEZRPnqC8spF-olYspC_M7ZVcV9XgS_UGuiQF1UfaD4tJwkFRLvdgPWhM_pyI3XusvAy290gG27G25FoFZp_nao_lJ7u0jGMI75Nm00)

2020-11-05 05:03 UTC, armiantos commented on doc/UML/MVVM-DetailedFragments-UML.txt
> +FilterMap <.. LibraryRepository: <<uses>>
After looking at MVVM-UML, it's fine to keep it in (analogous to BooksSource there)

2020-11-06 04:22 UTC, armiantos requested changes
Just one last nit, should be good to go after!

2020-11-06 04:22 UTC, armiantos commented on doc/UML/MVVM-DetailedFragments-UML.txt
> +LibraryBookDetailsFragment <.. CustomImageBinding: <<uses>>
```suggestion
LibraryEditBookFragment ..> BarcodeScanner: <<uses>>
LibraryEditBookFragment ..> FailedToScan: <<uses>>
LibraryEditBookFragment ..> CustomImageBinding: <<uses>>
LibraryBookDetailsFragment ..> CustomImageBinding: <<uses>>
```
I think the fragments use the util classes

2020-11-06 04:22 UTC, armiantos commented on doc/UML/MVVM-DetailedFragments-UML.txt
> +LibraryBookDetailsFragment <.. CustomImageBinding: <<uses>>
![](http://www.plantuml.com/plantuml/png/nLZlajes4F_kfz1CFvGCHnwWOQxXE2v7mq4A9krCftCZx3rGOyjKaabkCdttheGjOzRdSPBsmWTih_RFxc_Nkx9UQyELoTCa-750V-n6yMqAqcWsQFy5KSArPZEnKLmzbcBiSp0eIEy5VBpBOaXOwc-3GSbOC5q96GkvPMbnWmmYCQ3k-9wbwttC3Hm9GT0_P29ccHmhG6hlzJnF4hv9W5tbCiQBvWU8fnB3an6i3FAy2FhMifUn3xqPVynoCvKF2L8K4yND1REhRrIMxrcKISE5H6ARxd-20eArJ2W8IEm2WsSZG7oNU0FsvAyB4fDFqOxBBPm2KTBQSIYvA0nVWS9p9Dqxd6KVhW4b4tqQjO-Bij4GQTOmpipOKDb_xtdvvhKxJhY8tw--Zz-JM1ZhLSUEyug4L2gWyGpMIh1qb9liGIG9FfIaa7-0TxlCP4VQA3BY8CpZ4dIUc1dFPRG3DSJ5IvQk8Ywlk8hG-1W3L3moxI8dwYk1vy5su5uklSi-XXdNfhSooY6Yjmxtyzu-VFdoigLyVcB3eUG7iKNTcfdiyZAWp5GPpMcJfe3q5gUWf7PpXtPgfyIJksbf7fnLyN4PioNiCorCfWHATHobf5DYPHSP2KTlR9KVu9eRFfm9RORMrqii7dlLhwe-woq_ifJIaF4kDxQ1UcrE4Kl7kL8WNHhGB1eziamEI1pE-U5QA8YCoAH6vhb3n3wvTIfmz1ivRn3CNC6TtXuv-oJA7ewjfyItOCuK46xg7GfL_dcXHlIGrU5NOx0KjtG2YMKulYmWuoNydOCs9xG4eXgtUtaF-7V1X3JCeO_El0X-ACTP0bn1t3lfRpHPLVwNar_NarLuFrxCPfDnE5tC_TBLOl6sYRxuRJvP-gTLE0hNgteztI1c6wx1NZNQ0vPURsXzq6eB1fO64jGIjdYd7D8iRQ9wa-bwUXtqQP0MnO858L-BsCFAZU7HhbJgoP7hY6KEYYjJn-i5MyXL7aMWTIaulCwYtBxAItW01JA2IvQTCrcvej9A4ilEALsgoBaOGzrpJ7APPJAgFWTza7dAfdAVcxVmMC-HhPwxqU_tuJISJUvda_cRyBQYZjRXxM9P8qzNLtDFE2sHTxUBS76_2XVBIPSUG7cgMINTi6hKaW2No3NLiupReTgzCr3ETroeOGdB1Ii4hNPvu8c8tHAHxTYmMikxID9fAoMae5-GQesCGjBSI-geudg5grsca2AB1_MhU-3NjzcsVA0qoKY7ZajxOUq5htNT1_SDw1yrF_ZrrWvSRxybDyIYiRV7gCL0qmgs0Y65ta6yYdZPEyhjaj0RhzgKMxcUtJZcIZHhAD3kXJkLVNIVCtutve3a1a9X4YXD67mW7AFSx39Lid3tTCupHT_gVlfvGukycZUkYznCml7jFRQXMYDPqM7JEayysRhBKll_9VEZqppgarYw3H6NO_l7DlZtVyyEPpZVnvqC_ynqlaT5xr7ecspwkdvUcmzWefsrPdDsexBql18ls2-hnNon-GiYKmnnhpKX0TIIsA6taCCPMkU-RfitKi-rF-etU4WcoPTjE0W0PClHFlwQC4iRY46VAl-Mnjzz7rs5vuyBRLHuSUPUsk_RN5-mQaVYJn6zm8bP_-Mhwt8CfCq1CZwj6UEgAtEFBPxmlT_n_l4d4mRIuuFBvkR8LYmKGaK-QSF6hrUoeRGVhBa6xJztgOYdDmdH7RgJASbD8i6v3rRY_6IO-4K4FBb1X9YlETKW45I5qOuIPQmZrZ7EvhC3BzecIKy_EeRTPB8xoktIJvnoh0soTppFA4x1x7v7WlfSlY3L-LZFddV19yEYu_M25Picd3IrxL8rRZpvj0LW2127cUL4AwUFjHCjBp3EjS61b79_tbmwbsGyTlIU-tVjHvHtvPQNxRdPUL-Ttk2fmqbxl5J7eSAuJQWML4SH6XOLf4dl8FiQP9odoRy0)

2020-11-06 04:22 UTC, armiantos commented on doc/UML/MVVM-DetailedFragments-UML.txt
> +LibraryBookDetailsFragment <.. CustomImageBinding: <<uses>>
```suggestion
BarcodeScanner <.. LibraryEditBookFragment: <<uses>>
FailedToScan <.. LibraryEditBookFragment: <<uses>>
CustomImageBinding <.. LibraryEditBookFragment: <<uses>>
CustomImageBinding <.. LibraryBookDetailsFragment: <<uses>>
```
or this if you like the uses arrow pointing upwards 
![](http://www.plantuml.com/plantuml/png/nLZlRjis4F-kfo2m3tDXkm-m6baTnscyEdPdozs0OGXeYR6vIgH7Kcw3OE--8orHaayHr7HB_S6IZlVdxdUdEufljQ7AP6aI_3Z4FtAjw2vbmcWoRFy5KKAr9dE-LLGz56BaCHZcf8-SVRwLCKj8wc-3OS6OCrro4NEn8sb-0mmyCKpTqWD9DuUO6dOY147_A7bCf9We1jJUsqMM97IRC7APYHWkcXvPF1CGdeZOsW3Fgw1lBNiP-z2RqmUPcPcuJu2Y2Czl1iIklbCoEv182aEv06ARxd-278ADI308GEm2WsT3G7oNU0FovAyB4jClqPwA7Qi2KT3QSIYuC0pFGE4bakuTblBJ5GF9H5UZzd5XDXmYpXh4AOqDbVptdXTlNhlZY0lv_URx-3sDkR5UTUmuRr18XG8Spt2ZE4d7cP7tF4dWeI25z1Fxi9T6dcZZoF0ZDmyhfhF4p6aceZrJ8rYy8EawekAIgWYCJo10HIFJBb9HNmgy3BP3ztBflVmSIgfDRssKGqJl7ExdlNtq-lL5I_dyH4OZGOzy1xerCVBY8i3CM1dEQPEc0FKMfw2WTdC7Tsgdn9ExQMaUd6NnKH6J5Jj8pOrK7AGwZbBKAQ6oyuo4utUsoe_iYXewcdDjHjRN2oWUUzLloZxhBJ-G5DE0yJOpje5wRKuHIIUPKaouD81PC7fYcHw1E5hGunLNB39S2WtC2uU8VNBhME3aDt1U0vYPOhTwT-BieoXxCBQU4jynSwO0SoFlGAZqpmireWUi3hyQWwMufGeabk7qiZ0HhzZV6TEcGajOLEDsB-yH_WQ42qCS-k3Cg-27OfmbZ2eMzohz3IUhpFzg-kjckWxl9ilvV3e9Pyk5NxfSBjytqPU_BQOh_xGEn-5cNQ-dQy1iIpMpLmts64cljhW-SBK5GqjZWgaLsy6TSaYJj8dgJQQRsLNGnq5Q57CMW7p3OmyhDOP6-qAf9qUk8nOvoAz4dQu3iXJhB8gOreNWw4f6cNsLL-oUAIOYTa7aEPELookj815vJkbIHSx5cDKzXoGNMKQZwZ7eCv6bP2OEcNdF7kevijLpE_xzBfo5y-dTVBfu5zwKrF4cl5ckQkJP-dBX2TKI-N2p39Ttwt2vcdRf0PYdd5N23Qj6BGcZ0hXcUYwf7QhTEmFc_42v6XMm34WkQBMB8qrux9QGRCU6rLhUUPAghHIHWdvEgZKo34bpBwcZ2kibhdOPGmei7jHdzy3djjdsV80qoaYNZejxOVK5htNTU_SDw1yrFVhrrWvSRxy5DujvOs-FGOjXJIlG2hZWUi_YTKIBtb5ibxZUUjMcsChrxCOnKxnPGuvsBzmh-TbzplZTc0EI6XPoax32X847n37Ep5wgWeMwftEU6VXMzzFF6rpavRnnNUHw6avkxg0DrHh96WsRzddYoTPTajh_hvaVdUPH7yNIROYu7Di_ieM__tjsECFP8Uva-6UYimCe-WX2tsJJr_NBshnd9jfRQpPdrqgcvvKu8B-ibulbzYyMcNo8Uwq92g2Qn0wz1H_EDDUvBswyaNgf_L6_mKCyIRvgmu40G5kEzl7NX5dQG0pwMFctDFxk--WoF7zSQAE2YpFtsdxVPdf0oXs9FqNq0XMp_ijNr-K84pO7mFYqPeYhhimzjdX23tx7-yUVX1kMdXvSDhSdjdmX5yhpYHisVBsY3QNzOCqqq_vp5ujuUfCGtg4xcOBS91AS-s0bpa-6aLz8m9CRH93vcbCD0a5P6EqeOSOwObtZR3mxyA9jalZqesFOpIQxejmk_SGfnyO0UyVpZFmKpEvt15EFnGjIde_rx7aN-s98TBeEIBvfWabJsowLuyQJgoq0Gc1nA2qdMAa-rawqlC0aqmO6KahzUNFXN29fxEWzz-_Q3o_kYYqlEL2pzxuwlVLGEoQtwcX74UpvymKxr-vR9k8iJVu5)

2020-11-06 05:05 UTC, armiantos approved these changes
Looks good to me!

2020-11-06 05:08 UTC, Taranjot-Singh reviewed
The UML looks good! Thank you very much Cyrus!

Should I add a relationship between the Requests class and the Unlibrary Repository similar to how there is a relationship between the Request class and the Exchange Repository? My PR added this and Daniel's PR changed the Unlibrary ViewModel. I can make those changes if we think necessary.

Also I'm wondering: should we have composition between BooksFragment and BooksRecyclerViewAdapter instead of the aggregation?

2020-11-06 05:49 UTC, armiantos approved these changes
LGTM :beers: thank you for doing this @cyrusdiego

2020-11-06 05:50 UTC, Taranjot-Singh approved these changes

2020-11-06 05:57 UTC, merged