Golnoush/espresso ui tests
CMPUT301F20T24/Unlibrary pull request #97
Opened 2020-11-05 03:45 UTC by ghassanzadeh

# Summary
These are some sample UI tests for the login and Create profile pages. We do not need to merge this PR before making sure it won't cause our app to crash. 
- LoginActivityTest: tries to login with an already registered account
- CreateAccountTest: attempts to create an account in firstore
- CreateAccountCancelTest: tests the functionality of the cancel button on create profile page

@armiantos @Taranjot-Singh Thank you for helping me troubleshoot the test cases

# TODO
- Create a base class for login and the rest of the test extends from it as suggested by @cyrusdiego 
- @armiantos suggested changing the developer setting to always start the app from the login page
- Ensure to remove the created profile from firestore after the test otherwise the test will fail since the email is already registered in the firestore

Closes insert-issue-number-here

2020-11-05 04:08 UTC, cyrusdiego reviewed
Left some comments, overall looks good :D

2020-11-05 04:08 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/LoginActivityTest1.java
> +    public void loginActivityTest1() {
For UI testing the Login page I think this is fine, but I think for later UI tests we can just have a test like this:

```java
@RunWith(AndroidJUnit4.class)
public abstract class MockLogin {
    private final String mEmail = "cdiego@ualberta.ca";
    private final String mPassword = "password123";

    @Rule
    public final ActivityScenarioRule<MainActivity> activityScenarioRule = new ActivityScenarioRule<>(MainActivity.class);

    @Before
    public void login() {
        FirebaseAuth.getInstance().signInWithEmailAndPassword(mEmail, mPassword);
    }
}
```
This will just automatically login to the app without testing the UI before hand, but I think should still keep this current test as it tests the UI

2020-11-05 04:08 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/LoginActivityTest1.java
> +    public void loginActivityTest1() {
That's what I was using for setting up tests for the bottom navigation bar and I found it works pretty well :D

2020-11-05 04:08 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountTest.java
> +    private static Matcher<View> childAtPosition(
It looks like this is used in multiple test files, would we be able to store this in a `TestUtil` file?

2020-11-05 22:02 UTC, ghassanzadeh commented on app/src/androidTest/java/com/example/unlibrary/LoginActivityTest1.java
> +    public void loginActivityTest1() {
Sweet thanks @cyrusdiego!

2020-11-05 23:33 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/LoginActivityTest1.java
> +    public void loginActivityTest1() {
I have this in my PR #100 so can cross off that first TODO :D

2020-11-06 05:47 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> + * ExchangeFragment
nit: 
```suggestion
 * CreateAccountCancelTest
```

2020-11-06 05:48 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> + * ExchangeFragment
nit
```suggestion
 * CreateAccountPageUITest
```

2020-11-06 05:48 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/LoginPageUITest.java
> + * ExchangeFragment
nit
```suggestion
 * LoginPageUITest
```

2020-11-06 05:55 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +        ViewInteraction materialButton = onView(
I don't think we're quite validating that the UI changed state when we click the "Create Account" and "Cancel" button. One way to go about it is:

1) After clicking the "Create Account" button (line 57) we'd validate if the correct views are visible (i.e. the editText's and the title). Then after clicking "Cancel" we'd validate that these aren't visible anymore 

The issue with the current test is that we're only doing the click interactions but we're not validating the UI state (though some sort of assertion or `matches`)

2020-11-06 05:57 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +    public void createAccountPageUITest() {
Same idea as my previous comment, we're adding the text but we're not validating that the text is visible.

2020-11-06 07:29 UTC, ghassanzadeh commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +        ViewInteraction materialButton = onView(
I added onView(allOf(withId(R.id.register_title))).check(matches(withText("Register"))); and onView(allOf(withId(R.id.login_title))).check(matches(withText("Login"))); after clicking on cancel button

2020-11-06 07:31 UTC, ghassanzadeh commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +    public void createAccountPageUITest() {
should i remove isDisplayed() from the edittexts and only do onView(...).perform(typeText("Name"); ?

2020-11-06 07:43 UTC, ghassanzadeh commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +    public void createAccountPageUITest() {
added matches to check if the view is visible with Register as title and the edit texts

2020-11-18 01:47 UTC, cyrusdiego requested changes
Left some nits (you can probably just commit them directly in github). I ran the tests but for some reason they're failing :( they're not able to find the "Create Account" button and the login_email_input.

2020-11-18 01:47 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> + * UI Test
Nit: 
```suggestion
 * CreateAccountCancelTest
```

2020-11-18 01:47 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> + * UI Test
nit:
```suggestion
 * CreateAccountPageUITest
```

2020-11-18 01:47 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/LoginPageUITest.java
> + * UI Test
nit:
```suggestion
 * LoginPageUITest
```

2020-11-21 06:32 UTC, armiantos reviewed
Left some comments to consider before merging this. 

Regarding Login tests, since instrumented tests are running on Firebase test labs, there's no way I can get the local emulator I explored earlier last week. So they must interact with our production database. I'm not sure if google-services.json secret in Github is baked in to the app when we compile (need @calebschoepp's input on this), if so we can store a different collection there for testing.

2020-11-21 06:32 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +        onView(withId(R.id.login_password_input));
Are these not doing checks?

2020-11-21 06:32 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +    private static Matcher<View> childAtPosition(
I believe this was autogenerated. Could you include a brief description for this function infering to what it's being used for e.g. returns the child of given view?

2020-11-21 06:32 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +        onView(withId(R.id.login_password_input));
Same here (are they doing anything)?

2020-11-21 06:32 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +    }
Should we also verify that the password is displayed?

2020-11-22 05:14 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +        onView(withId(R.id.login_password_input));
the `onView` will check if they're visible I think for UI tests that should suffice. Or if we want, we can add code to enter input in the input field then verify the input fields have the correct strings

2020-11-22 05:14 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +        onView(withId(R.id.login_password_input));
refer to my prev comment

2020-11-22 19:27 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +        onView(withId(R.id.login_password_input));
Ah got it, thanks! No I though we had to do like `.check(isPresent())` to achieve this but it makes sense since onView returns the view before it can be interacted with and will fail if it cant find it

2020-11-24 05:49 UTC, ghassanzadeh commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +    }
I remember we had a conversation with Cyrus about "show password" and decided to remove it as it is not really related to create account or login. I can definitely add it back. :D

2020-11-25 21:45 UTC, armiantos requested changes
We're getting there! Just a few more nits and a final clean up. We should also consider refactoring the `childAtPosition` static (likely in a separate PR)

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +//        onView(allOf(withId(R.id.register_title), withText("Register")));
I think this is a replacement for line 61, so I think we should just remove it

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +    // https://developer.android.com/training/testing/espresso/basics
This can be removed too since its Android's documentation

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +//        onView(allOf(withId(R.id.login_title), withText("Login")));
Same here

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +     * verifies the position of the child in a given view
```suggestion
     * Verifies the position of the child in a given view
```
Nit

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +@LargeTest
Really interesting topic if anyone wants to read about actually [ref](https://developer.android.com/reference/androidx/test/filters/LargeTest). I think this just ensures when running the whole suite, these tests are run last so that smaller tests can be done in parallel? Correct me if I'm wrong tho

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +//        onView(allOf(withId(R.id.register_title), withText("Register")));
Same here

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/LoginActivityTest1.java
> + * Copyright (c) Team 24, Fall2020, CMPUT301, University of Alberta
Are we keeping this file?

2020-11-25 21:45 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/LoginPageUITest.java
> +        textInputEditText.perform(replaceText("golnoush@gmail.com"), closeSoftKeyboard());
If we decide to merge #139 first, could we alter this to the common ui test account

2020-11-26 00:54 UTC, ghassanzadeh commented on app/src/androidTest/java/com/example/unlibrary/LoginPageUITest.java
> +        textInputEditText.perform(replaceText("golnoush@gmail.com"), closeSoftKeyboard());
Yes, I'll change it now.

2020-11-26 17:43 UTC, cyrusdiego reviewed
just left some nits, ping me when you get the logout thing pushed and I can take a look :D good work on this !

2020-11-26 17:43 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountCancelTest.java
> +
Nit: extra line

2020-11-26 17:43 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +
nit: extra line

2020-11-26 17:43 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/LoginPageUITest.java
> +
nit: extra line

2020-11-26 17:43 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/LoginPageUITest.java
> +     * verifies the position of the child in a given view
nit
```suggestion
     * Verifies the position of the child in a given view
```

2020-11-26 17:43 UTC, cyrusdiego commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +     * verifies the position of the child in a given view
nit
```suggestion
     * Verifies the position of the child in a given view
```

2020-11-26 17:43 UTC, cyrusdiego commented on app/build.gradle
> +    // androidTestImplementation 'androidx.test:rules:1.3.0'
can we remove this?

2020-11-26 19:37 UTC, armiantos commented on app/src/androidTest/java/com/example/unlibrary/CreateAccountPageUITest.java
> +     * verifies the position of the child in a given view
Also doesn't this return the child view?

2020-11-26 19:37 UTC, armiantos reviewed
Other than the nits mentioned by @cyrusdiego it looks good!

2020-11-28 16:59 UTC, cyrusdiego commented
Requires #147 to be merged first

2020-11-28 21:10 UTC, cyrusdiego approved these changes
LGTM!

2020-11-28 21:13 UTC, armiantos approved these changes
LGTM! :100:

2020-11-28 21:13 UTC, merged